edition = "2023";

package logins;

import "google/protobuf/wrappers.proto";

option go_package = "github.com/artni96/GophKeeper/api/proto/logins";

service LoginService {
  rpc CreateLogin (LoginCreateRequest) returns (LoginCreateResponse);
  rpc GetLogin (LoginGetRequest) returns (LoginGetResponse);
  rpc UpdateLogin (LoginUpdateRequest) returns (LoginUpdateResponse);
  rpc DeleteLogin (LoginDeleteRequest) returns (LoginDeleteResponse);
  rpc GetListLogin (LoginGetListRequest) returns (LoginGetListResponse);
}

message LoginCreateRequest {
  google.protobuf.StringValue title = 1;
  google.protobuf.StringValue url = 2;
  google.protobuf.StringValue description = 3;
  google.protobuf.BytesValue login = 4;
  google.protobuf.BytesValue password = 5;
  google.protobuf.BytesValue nonce = 6;
  google.protobuf.UInt64Value key_id = 7;
}

message LoginCreateResponse {
  uint64 number = 1;
}

message LoginGetRequest {
  uint64 number = 1;
}

message LoginGetResponse {
  string title = 1;
  uint64 number = 2;
  string url = 3;
  string description = 4;
  bytes login = 5;
  bytes password = 6;
  bytes nonce = 7;
  uint64 key_id = 8;
  string created_at = 9;
  string updated_at = 10;
}

message LoginUpdateRequest {
  google.protobuf.StringValue title = 1;
  google.protobuf.StringValue url = 2;
  google.protobuf.StringValue description = 3;
  google.protobuf.BytesValue login = 4;
  google.protobuf.BytesValue password = 5;
  google.protobuf.BytesValue nonce = 6;
  google.protobuf.UInt64Value key_id = 7;
  uint64 number = 8;
}

message LoginUpdateResponse {
}

message LoginDeleteRequest {
  uint64 number = 1;
}

message LoginDeleteResponse {
}

message LoginGetListRequest {
}

message LoginGetListResponse {
  repeated LoginGetResponse logins = 1;
}
