// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/logins/logins.proto

package logins

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginCreateRequest struct {
	state                    protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Title         *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=title"`
	xxx_hidden_Url           *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=url"`
	xxx_hidden_Description   *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=description"`
	xxx_hidden_LoginValue    *wrapperspb.BytesValue  `protobuf:"bytes,4,opt,name=login_value,json=loginValue"`
	xxx_hidden_LoginNonce    *wrapperspb.BytesValue  `protobuf:"bytes,5,opt,name=login_nonce,json=loginNonce"`
	xxx_hidden_LoginKeyId    *wrapperspb.UInt64Value `protobuf:"bytes,6,opt,name=login_key_id,json=loginKeyId"`
	xxx_hidden_PasswordValue *wrapperspb.BytesValue  `protobuf:"bytes,7,opt,name=password_value,json=passwordValue"`
	xxx_hidden_PasswordNonce *wrapperspb.BytesValue  `protobuf:"bytes,8,opt,name=password_nonce,json=passwordNonce"`
	xxx_hidden_PasswordKeyId *wrapperspb.UInt64Value `protobuf:"bytes,9,opt,name=password_key_id,json=passwordKeyId"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *LoginCreateRequest) Reset() {
	*x = LoginCreateRequest{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCreateRequest) ProtoMessage() {}

func (x *LoginCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginCreateRequest) GetTitle() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return nil
}

func (x *LoginCreateRequest) GetUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Url
	}
	return nil
}

func (x *LoginCreateRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return nil
}

func (x *LoginCreateRequest) GetLoginValue() *wrapperspb.BytesValue {
	if x != nil {
		return x.xxx_hidden_LoginValue
	}
	return nil
}

func (x *LoginCreateRequest) GetLoginNonce() *wrapperspb.BytesValue {
	if x != nil {
		return x.xxx_hidden_LoginNonce
	}
	return nil
}

func (x *LoginCreateRequest) GetLoginKeyId() *wrapperspb.UInt64Value {
	if x != nil {
		return x.xxx_hidden_LoginKeyId
	}
	return nil
}

func (x *LoginCreateRequest) GetPasswordValue() *wrapperspb.BytesValue {
	if x != nil {
		return x.xxx_hidden_PasswordValue
	}
	return nil
}

func (x *LoginCreateRequest) GetPasswordNonce() *wrapperspb.BytesValue {
	if x != nil {
		return x.xxx_hidden_PasswordNonce
	}
	return nil
}

func (x *LoginCreateRequest) GetPasswordKeyId() *wrapperspb.UInt64Value {
	if x != nil {
		return x.xxx_hidden_PasswordKeyId
	}
	return nil
}

func (x *LoginCreateRequest) SetTitle(v *wrapperspb.StringValue) {
	x.xxx_hidden_Title = v
}

func (x *LoginCreateRequest) SetUrl(v *wrapperspb.StringValue) {
	x.xxx_hidden_Url = v
}

func (x *LoginCreateRequest) SetDescription(v *wrapperspb.StringValue) {
	x.xxx_hidden_Description = v
}

func (x *LoginCreateRequest) SetLoginValue(v *wrapperspb.BytesValue) {
	x.xxx_hidden_LoginValue = v
}

func (x *LoginCreateRequest) SetLoginNonce(v *wrapperspb.BytesValue) {
	x.xxx_hidden_LoginNonce = v
}

func (x *LoginCreateRequest) SetLoginKeyId(v *wrapperspb.UInt64Value) {
	x.xxx_hidden_LoginKeyId = v
}

func (x *LoginCreateRequest) SetPasswordValue(v *wrapperspb.BytesValue) {
	x.xxx_hidden_PasswordValue = v
}

func (x *LoginCreateRequest) SetPasswordNonce(v *wrapperspb.BytesValue) {
	x.xxx_hidden_PasswordNonce = v
}

func (x *LoginCreateRequest) SetPasswordKeyId(v *wrapperspb.UInt64Value) {
	x.xxx_hidden_PasswordKeyId = v
}

func (x *LoginCreateRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Title != nil
}

func (x *LoginCreateRequest) HasUrl() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Url != nil
}

func (x *LoginCreateRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Description != nil
}

func (x *LoginCreateRequest) HasLoginValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LoginValue != nil
}

func (x *LoginCreateRequest) HasLoginNonce() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LoginNonce != nil
}

func (x *LoginCreateRequest) HasLoginKeyId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LoginKeyId != nil
}

func (x *LoginCreateRequest) HasPasswordValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PasswordValue != nil
}

func (x *LoginCreateRequest) HasPasswordNonce() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PasswordNonce != nil
}

func (x *LoginCreateRequest) HasPasswordKeyId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PasswordKeyId != nil
}

func (x *LoginCreateRequest) ClearTitle() {
	x.xxx_hidden_Title = nil
}

func (x *LoginCreateRequest) ClearUrl() {
	x.xxx_hidden_Url = nil
}

func (x *LoginCreateRequest) ClearDescription() {
	x.xxx_hidden_Description = nil
}

func (x *LoginCreateRequest) ClearLoginValue() {
	x.xxx_hidden_LoginValue = nil
}

func (x *LoginCreateRequest) ClearLoginNonce() {
	x.xxx_hidden_LoginNonce = nil
}

func (x *LoginCreateRequest) ClearLoginKeyId() {
	x.xxx_hidden_LoginKeyId = nil
}

func (x *LoginCreateRequest) ClearPasswordValue() {
	x.xxx_hidden_PasswordValue = nil
}

func (x *LoginCreateRequest) ClearPasswordNonce() {
	x.xxx_hidden_PasswordNonce = nil
}

func (x *LoginCreateRequest) ClearPasswordKeyId() {
	x.xxx_hidden_PasswordKeyId = nil
}

type LoginCreateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title         *wrapperspb.StringValue
	Url           *wrapperspb.StringValue
	Description   *wrapperspb.StringValue
	LoginValue    *wrapperspb.BytesValue
	LoginNonce    *wrapperspb.BytesValue
	LoginKeyId    *wrapperspb.UInt64Value
	PasswordValue *wrapperspb.BytesValue
	PasswordNonce *wrapperspb.BytesValue
	PasswordKeyId *wrapperspb.UInt64Value
}

func (b0 LoginCreateRequest_builder) Build() *LoginCreateRequest {
	m0 := &LoginCreateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Url = b.Url
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_LoginValue = b.LoginValue
	x.xxx_hidden_LoginNonce = b.LoginNonce
	x.xxx_hidden_LoginKeyId = b.LoginKeyId
	x.xxx_hidden_PasswordValue = b.PasswordValue
	x.xxx_hidden_PasswordNonce = b.PasswordNonce
	x.xxx_hidden_PasswordKeyId = b.PasswordKeyId
	return m0
}

type LoginCreateResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Number      uint64                 `protobuf:"varint,1,opt,name=number"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginCreateResponse) Reset() {
	*x = LoginCreateResponse{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCreateResponse) ProtoMessage() {}

func (x *LoginCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginCreateResponse) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *LoginCreateResponse) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *LoginCreateResponse) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginCreateResponse) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Number = 0
}

type LoginCreateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Number *uint64
}

func (b0 LoginCreateResponse_builder) Build() *LoginCreateResponse {
	m0 := &LoginCreateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Number = *b.Number
	}
	return m0
}

type LoginGetRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Number      uint64                 `protobuf:"varint,1,opt,name=number"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginGetRequest) Reset() {
	*x = LoginGetRequest{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGetRequest) ProtoMessage() {}

func (x *LoginGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginGetRequest) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *LoginGetRequest) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *LoginGetRequest) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginGetRequest) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Number = 0
}

type LoginGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Number *uint64
}

func (b0 LoginGetRequest_builder) Build() *LoginGetRequest {
	m0 := &LoginGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Number = *b.Number
	}
	return m0
}

type LoginGetResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Title         *string                `protobuf:"bytes,1,opt,name=title"`
	xxx_hidden_Number        uint64                 `protobuf:"varint,2,opt,name=number"`
	xxx_hidden_Url           *string                `protobuf:"bytes,3,opt,name=url"`
	xxx_hidden_Description   *string                `protobuf:"bytes,4,opt,name=description"`
	xxx_hidden_LoginValue    []byte                 `protobuf:"bytes,5,opt,name=login_value,json=loginValue"`
	xxx_hidden_LoginNonce    []byte                 `protobuf:"bytes,6,opt,name=login_nonce,json=loginNonce"`
	xxx_hidden_LoginKeyId    uint64                 `protobuf:"varint,7,opt,name=login_key_id,json=loginKeyId"`
	xxx_hidden_PasswordValue []byte                 `protobuf:"bytes,8,opt,name=password_value,json=passwordValue"`
	xxx_hidden_PasswordNonce []byte                 `protobuf:"bytes,9,opt,name=password_nonce,json=passwordNonce"`
	xxx_hidden_PasswordKeyId uint64                 `protobuf:"varint,10,opt,name=password_key_id,json=passwordKeyId"`
	xxx_hidden_CreatedAt     *string                `protobuf:"bytes,11,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt     *string                `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *LoginGetResponse) Reset() {
	*x = LoginGetResponse{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGetResponse) ProtoMessage() {}

func (x *LoginGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginGetResponse) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *LoginGetResponse) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *LoginGetResponse) GetUrl() string {
	if x != nil {
		if x.xxx_hidden_Url != nil {
			return *x.xxx_hidden_Url
		}
		return ""
	}
	return ""
}

func (x *LoginGetResponse) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *LoginGetResponse) GetLoginValue() []byte {
	if x != nil {
		return x.xxx_hidden_LoginValue
	}
	return nil
}

func (x *LoginGetResponse) GetLoginNonce() []byte {
	if x != nil {
		return x.xxx_hidden_LoginNonce
	}
	return nil
}

func (x *LoginGetResponse) GetLoginKeyId() uint64 {
	if x != nil {
		return x.xxx_hidden_LoginKeyId
	}
	return 0
}

func (x *LoginGetResponse) GetPasswordValue() []byte {
	if x != nil {
		return x.xxx_hidden_PasswordValue
	}
	return nil
}

func (x *LoginGetResponse) GetPasswordNonce() []byte {
	if x != nil {
		return x.xxx_hidden_PasswordNonce
	}
	return nil
}

func (x *LoginGetResponse) GetPasswordKeyId() uint64 {
	if x != nil {
		return x.xxx_hidden_PasswordKeyId
	}
	return 0
}

func (x *LoginGetResponse) GetCreatedAt() string {
	if x != nil {
		if x.xxx_hidden_CreatedAt != nil {
			return *x.xxx_hidden_CreatedAt
		}
		return ""
	}
	return ""
}

func (x *LoginGetResponse) GetUpdatedAt() string {
	if x != nil {
		if x.xxx_hidden_UpdatedAt != nil {
			return *x.xxx_hidden_UpdatedAt
		}
		return ""
	}
	return ""
}

func (x *LoginGetResponse) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 12)
}

func (x *LoginGetResponse) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 12)
}

func (x *LoginGetResponse) SetUrl(v string) {
	x.xxx_hidden_Url = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 12)
}

func (x *LoginGetResponse) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 12)
}

func (x *LoginGetResponse) SetLoginValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_LoginValue = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 12)
}

func (x *LoginGetResponse) SetLoginNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_LoginNonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 12)
}

func (x *LoginGetResponse) SetLoginKeyId(v uint64) {
	x.xxx_hidden_LoginKeyId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 12)
}

func (x *LoginGetResponse) SetPasswordValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_PasswordValue = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 12)
}

func (x *LoginGetResponse) SetPasswordNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_PasswordNonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 12)
}

func (x *LoginGetResponse) SetPasswordKeyId(v uint64) {
	x.xxx_hidden_PasswordKeyId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 12)
}

func (x *LoginGetResponse) SetCreatedAt(v string) {
	x.xxx_hidden_CreatedAt = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 12)
}

func (x *LoginGetResponse) SetUpdatedAt(v string) {
	x.xxx_hidden_UpdatedAt = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 12)
}

func (x *LoginGetResponse) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginGetResponse) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LoginGetResponse) HasUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *LoginGetResponse) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *LoginGetResponse) HasLoginValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *LoginGetResponse) HasLoginNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *LoginGetResponse) HasLoginKeyId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *LoginGetResponse) HasPasswordValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *LoginGetResponse) HasPasswordNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *LoginGetResponse) HasPasswordKeyId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *LoginGetResponse) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *LoginGetResponse) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *LoginGetResponse) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Title = nil
}

func (x *LoginGetResponse) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Number = 0
}

func (x *LoginGetResponse) ClearUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Url = nil
}

func (x *LoginGetResponse) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Description = nil
}

func (x *LoginGetResponse) ClearLoginValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_LoginValue = nil
}

func (x *LoginGetResponse) ClearLoginNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_LoginNonce = nil
}

func (x *LoginGetResponse) ClearLoginKeyId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_LoginKeyId = 0
}

func (x *LoginGetResponse) ClearPasswordValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_PasswordValue = nil
}

func (x *LoginGetResponse) ClearPasswordNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_PasswordNonce = nil
}

func (x *LoginGetResponse) ClearPasswordKeyId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_PasswordKeyId = 0
}

func (x *LoginGetResponse) ClearCreatedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_CreatedAt = nil
}

func (x *LoginGetResponse) ClearUpdatedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_UpdatedAt = nil
}

type LoginGetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title         *string
	Number        *uint64
	Url           *string
	Description   *string
	LoginValue    []byte
	LoginNonce    []byte
	LoginKeyId    *uint64
	PasswordValue []byte
	PasswordNonce []byte
	PasswordKeyId *uint64
	CreatedAt     *string
	UpdatedAt     *string
}

func (b0 LoginGetResponse_builder) Build() *LoginGetResponse {
	m0 := &LoginGetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 12)
		x.xxx_hidden_Title = b.Title
	}
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 12)
		x.xxx_hidden_Number = *b.Number
	}
	if b.Url != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 12)
		x.xxx_hidden_Url = b.Url
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 12)
		x.xxx_hidden_Description = b.Description
	}
	if b.LoginValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 12)
		x.xxx_hidden_LoginValue = b.LoginValue
	}
	if b.LoginNonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 12)
		x.xxx_hidden_LoginNonce = b.LoginNonce
	}
	if b.LoginKeyId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 12)
		x.xxx_hidden_LoginKeyId = *b.LoginKeyId
	}
	if b.PasswordValue != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 12)
		x.xxx_hidden_PasswordValue = b.PasswordValue
	}
	if b.PasswordNonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 12)
		x.xxx_hidden_PasswordNonce = b.PasswordNonce
	}
	if b.PasswordKeyId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 12)
		x.xxx_hidden_PasswordKeyId = *b.PasswordKeyId
	}
	if b.CreatedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 12)
		x.xxx_hidden_CreatedAt = b.CreatedAt
	}
	if b.UpdatedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 12)
		x.xxx_hidden_UpdatedAt = b.UpdatedAt
	}
	return m0
}

type LoginUpdateRequest struct {
	state                    protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Title         *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=title"`
	xxx_hidden_Url           *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=url"`
	xxx_hidden_Description   *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=description"`
	xxx_hidden_LoginValue    *wrapperspb.BytesValue  `protobuf:"bytes,4,opt,name=login_value,json=loginValue"`
	xxx_hidden_LoginNonce    *wrapperspb.BytesValue  `protobuf:"bytes,5,opt,name=login_nonce,json=loginNonce"`
	xxx_hidden_LoginKeyId    *wrapperspb.UInt64Value `protobuf:"bytes,6,opt,name=login_key_id,json=loginKeyId"`
	xxx_hidden_PasswordValue *wrapperspb.BytesValue  `protobuf:"bytes,7,opt,name=password_value,json=passwordValue"`
	xxx_hidden_PasswordNonce *wrapperspb.BytesValue  `protobuf:"bytes,8,opt,name=password_nonce,json=passwordNonce"`
	xxx_hidden_PasswordKeyId *wrapperspb.UInt64Value `protobuf:"bytes,9,opt,name=password_key_id,json=passwordKeyId"`
	xxx_hidden_Number        uint64                  `protobuf:"varint,10,opt,name=number"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *LoginUpdateRequest) Reset() {
	*x = LoginUpdateRequest{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUpdateRequest) ProtoMessage() {}

func (x *LoginUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginUpdateRequest) GetTitle() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return nil
}

func (x *LoginUpdateRequest) GetUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Url
	}
	return nil
}

func (x *LoginUpdateRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return nil
}

func (x *LoginUpdateRequest) GetLoginValue() *wrapperspb.BytesValue {
	if x != nil {
		return x.xxx_hidden_LoginValue
	}
	return nil
}

func (x *LoginUpdateRequest) GetLoginNonce() *wrapperspb.BytesValue {
	if x != nil {
		return x.xxx_hidden_LoginNonce
	}
	return nil
}

func (x *LoginUpdateRequest) GetLoginKeyId() *wrapperspb.UInt64Value {
	if x != nil {
		return x.xxx_hidden_LoginKeyId
	}
	return nil
}

func (x *LoginUpdateRequest) GetPasswordValue() *wrapperspb.BytesValue {
	if x != nil {
		return x.xxx_hidden_PasswordValue
	}
	return nil
}

func (x *LoginUpdateRequest) GetPasswordNonce() *wrapperspb.BytesValue {
	if x != nil {
		return x.xxx_hidden_PasswordNonce
	}
	return nil
}

func (x *LoginUpdateRequest) GetPasswordKeyId() *wrapperspb.UInt64Value {
	if x != nil {
		return x.xxx_hidden_PasswordKeyId
	}
	return nil
}

func (x *LoginUpdateRequest) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *LoginUpdateRequest) SetTitle(v *wrapperspb.StringValue) {
	x.xxx_hidden_Title = v
}

func (x *LoginUpdateRequest) SetUrl(v *wrapperspb.StringValue) {
	x.xxx_hidden_Url = v
}

func (x *LoginUpdateRequest) SetDescription(v *wrapperspb.StringValue) {
	x.xxx_hidden_Description = v
}

func (x *LoginUpdateRequest) SetLoginValue(v *wrapperspb.BytesValue) {
	x.xxx_hidden_LoginValue = v
}

func (x *LoginUpdateRequest) SetLoginNonce(v *wrapperspb.BytesValue) {
	x.xxx_hidden_LoginNonce = v
}

func (x *LoginUpdateRequest) SetLoginKeyId(v *wrapperspb.UInt64Value) {
	x.xxx_hidden_LoginKeyId = v
}

func (x *LoginUpdateRequest) SetPasswordValue(v *wrapperspb.BytesValue) {
	x.xxx_hidden_PasswordValue = v
}

func (x *LoginUpdateRequest) SetPasswordNonce(v *wrapperspb.BytesValue) {
	x.xxx_hidden_PasswordNonce = v
}

func (x *LoginUpdateRequest) SetPasswordKeyId(v *wrapperspb.UInt64Value) {
	x.xxx_hidden_PasswordKeyId = v
}

func (x *LoginUpdateRequest) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 10)
}

func (x *LoginUpdateRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Title != nil
}

func (x *LoginUpdateRequest) HasUrl() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Url != nil
}

func (x *LoginUpdateRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Description != nil
}

func (x *LoginUpdateRequest) HasLoginValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LoginValue != nil
}

func (x *LoginUpdateRequest) HasLoginNonce() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LoginNonce != nil
}

func (x *LoginUpdateRequest) HasLoginKeyId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LoginKeyId != nil
}

func (x *LoginUpdateRequest) HasPasswordValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PasswordValue != nil
}

func (x *LoginUpdateRequest) HasPasswordNonce() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PasswordNonce != nil
}

func (x *LoginUpdateRequest) HasPasswordKeyId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PasswordKeyId != nil
}

func (x *LoginUpdateRequest) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *LoginUpdateRequest) ClearTitle() {
	x.xxx_hidden_Title = nil
}

func (x *LoginUpdateRequest) ClearUrl() {
	x.xxx_hidden_Url = nil
}

func (x *LoginUpdateRequest) ClearDescription() {
	x.xxx_hidden_Description = nil
}

func (x *LoginUpdateRequest) ClearLoginValue() {
	x.xxx_hidden_LoginValue = nil
}

func (x *LoginUpdateRequest) ClearLoginNonce() {
	x.xxx_hidden_LoginNonce = nil
}

func (x *LoginUpdateRequest) ClearLoginKeyId() {
	x.xxx_hidden_LoginKeyId = nil
}

func (x *LoginUpdateRequest) ClearPasswordValue() {
	x.xxx_hidden_PasswordValue = nil
}

func (x *LoginUpdateRequest) ClearPasswordNonce() {
	x.xxx_hidden_PasswordNonce = nil
}

func (x *LoginUpdateRequest) ClearPasswordKeyId() {
	x.xxx_hidden_PasswordKeyId = nil
}

func (x *LoginUpdateRequest) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Number = 0
}

type LoginUpdateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title         *wrapperspb.StringValue
	Url           *wrapperspb.StringValue
	Description   *wrapperspb.StringValue
	LoginValue    *wrapperspb.BytesValue
	LoginNonce    *wrapperspb.BytesValue
	LoginKeyId    *wrapperspb.UInt64Value
	PasswordValue *wrapperspb.BytesValue
	PasswordNonce *wrapperspb.BytesValue
	PasswordKeyId *wrapperspb.UInt64Value
	Number        *uint64
}

func (b0 LoginUpdateRequest_builder) Build() *LoginUpdateRequest {
	m0 := &LoginUpdateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Url = b.Url
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_LoginValue = b.LoginValue
	x.xxx_hidden_LoginNonce = b.LoginNonce
	x.xxx_hidden_LoginKeyId = b.LoginKeyId
	x.xxx_hidden_PasswordValue = b.PasswordValue
	x.xxx_hidden_PasswordNonce = b.PasswordNonce
	x.xxx_hidden_PasswordKeyId = b.PasswordKeyId
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 10)
		x.xxx_hidden_Number = *b.Number
	}
	return m0
}

type LoginUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUpdateResponse) Reset() {
	*x = LoginUpdateResponse{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUpdateResponse) ProtoMessage() {}

func (x *LoginUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LoginUpdateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 LoginUpdateResponse_builder) Build() *LoginUpdateResponse {
	m0 := &LoginUpdateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type LoginDeleteRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Number      uint64                 `protobuf:"varint,1,opt,name=number"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginDeleteRequest) Reset() {
	*x = LoginDeleteRequest{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginDeleteRequest) ProtoMessage() {}

func (x *LoginDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginDeleteRequest) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *LoginDeleteRequest) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *LoginDeleteRequest) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginDeleteRequest) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Number = 0
}

type LoginDeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Number *uint64
}

func (b0 LoginDeleteRequest_builder) Build() *LoginDeleteRequest {
	m0 := &LoginDeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Number = *b.Number
	}
	return m0
}

type LoginDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginDeleteResponse) Reset() {
	*x = LoginDeleteResponse{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginDeleteResponse) ProtoMessage() {}

func (x *LoginDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LoginDeleteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 LoginDeleteResponse_builder) Build() *LoginDeleteResponse {
	m0 := &LoginDeleteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type LoginGetListRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginGetListRequest) Reset() {
	*x = LoginGetListRequest{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginGetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGetListRequest) ProtoMessage() {}

func (x *LoginGetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LoginGetListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 LoginGetListRequest_builder) Build() *LoginGetListRequest {
	m0 := &LoginGetListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type LoginGetListResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Logins *[]*LoginGetResponse   `protobuf:"bytes,1,rep,name=logins"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LoginGetListResponse) Reset() {
	*x = LoginGetListResponse{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginGetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGetListResponse) ProtoMessage() {}

func (x *LoginGetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginGetListResponse) GetLogins() []*LoginGetResponse {
	if x != nil {
		if x.xxx_hidden_Logins != nil {
			return *x.xxx_hidden_Logins
		}
	}
	return nil
}

func (x *LoginGetListResponse) SetLogins(v []*LoginGetResponse) {
	x.xxx_hidden_Logins = &v
}

type LoginGetListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Logins []*LoginGetResponse
}

func (b0 LoginGetListResponse_builder) Build() *LoginGetListResponse {
	m0 := &LoginGetListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Logins = &b.Logins
	return m0
}

var File_api_proto_logins_logins_proto protoreflect.FileDescriptor

const file_api_proto_logins_logins_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/logins/logins.proto\x12\x06logins\x1a\x1egoogle/protobuf/wrappers.proto\"\xc2\x04\n" +
	"\x12LoginCreateRequest\x122\n" +
	"\x05title\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x05title\x12.\n" +
	"\x03url\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x03url\x12>\n" +
	"\vdescription\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12<\n" +
	"\vlogin_value\x18\x04 \x01(\v2\x1b.google.protobuf.BytesValueR\n" +
	"loginValue\x12<\n" +
	"\vlogin_nonce\x18\x05 \x01(\v2\x1b.google.protobuf.BytesValueR\n" +
	"loginNonce\x12>\n" +
	"\flogin_key_id\x18\x06 \x01(\v2\x1c.google.protobuf.UInt64ValueR\n" +
	"loginKeyId\x12B\n" +
	"\x0epassword_value\x18\a \x01(\v2\x1b.google.protobuf.BytesValueR\rpasswordValue\x12B\n" +
	"\x0epassword_nonce\x18\b \x01(\v2\x1b.google.protobuf.BytesValueR\rpasswordNonce\x12D\n" +
	"\x0fpassword_key_id\x18\t \x01(\v2\x1c.google.protobuf.UInt64ValueR\rpasswordKeyId\"-\n" +
	"\x13LoginCreateResponse\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\")\n" +
	"\x0fLoginGetRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\"\x8c\x03\n" +
	"\x10LoginGetResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x04R\x06number\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vlogin_value\x18\x05 \x01(\fR\n" +
	"loginValue\x12\x1f\n" +
	"\vlogin_nonce\x18\x06 \x01(\fR\n" +
	"loginNonce\x12 \n" +
	"\flogin_key_id\x18\a \x01(\x04R\n" +
	"loginKeyId\x12%\n" +
	"\x0epassword_value\x18\b \x01(\fR\rpasswordValue\x12%\n" +
	"\x0epassword_nonce\x18\t \x01(\fR\rpasswordNonce\x12&\n" +
	"\x0fpassword_key_id\x18\n" +
	" \x01(\x04R\rpasswordKeyId\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\xda\x04\n" +
	"\x12LoginUpdateRequest\x122\n" +
	"\x05title\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x05title\x12.\n" +
	"\x03url\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x03url\x12>\n" +
	"\vdescription\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12<\n" +
	"\vlogin_value\x18\x04 \x01(\v2\x1b.google.protobuf.BytesValueR\n" +
	"loginValue\x12<\n" +
	"\vlogin_nonce\x18\x05 \x01(\v2\x1b.google.protobuf.BytesValueR\n" +
	"loginNonce\x12>\n" +
	"\flogin_key_id\x18\x06 \x01(\v2\x1c.google.protobuf.UInt64ValueR\n" +
	"loginKeyId\x12B\n" +
	"\x0epassword_value\x18\a \x01(\v2\x1b.google.protobuf.BytesValueR\rpasswordValue\x12B\n" +
	"\x0epassword_nonce\x18\b \x01(\v2\x1b.google.protobuf.BytesValueR\rpasswordNonce\x12D\n" +
	"\x0fpassword_key_id\x18\t \x01(\v2\x1c.google.protobuf.UInt64ValueR\rpasswordKeyId\x12\x16\n" +
	"\x06number\x18\n" +
	" \x01(\x04R\x06number\"\x15\n" +
	"\x13LoginUpdateResponse\",\n" +
	"\x12LoginDeleteRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\"\x15\n" +
	"\x13LoginDeleteResponse\"\x15\n" +
	"\x13LoginGetListRequest\"H\n" +
	"\x14LoginGetListResponse\x120\n" +
	"\x06logins\x18\x01 \x03(\v2\x18.logins.LoginGetResponseR\x06logins2\xf0\x02\n" +
	"\fLoginService\x12F\n" +
	"\vCreateLogin\x12\x1a.logins.LoginCreateRequest\x1a\x1b.logins.LoginCreateResponse\x12=\n" +
	"\bGetLogin\x12\x17.logins.LoginGetRequest\x1a\x18.logins.LoginGetResponse\x12F\n" +
	"\vUpdateLogin\x12\x1a.logins.LoginUpdateRequest\x1a\x1b.logins.LoginUpdateResponse\x12F\n" +
	"\vDeleteLogin\x12\x1a.logins.LoginDeleteRequest\x1a\x1b.logins.LoginDeleteResponse\x12I\n" +
	"\fGetListLogin\x12\x1b.logins.LoginGetListRequest\x1a\x1c.logins.LoginGetListResponseB0Z.github.com/artni96/GophKeeper/api/proto/loginsb\beditionsp\xe8\a"

var file_api_proto_logins_logins_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_logins_logins_proto_goTypes = []any{
	(*LoginCreateRequest)(nil),     // 0: logins.LoginCreateRequest
	(*LoginCreateResponse)(nil),    // 1: logins.LoginCreateResponse
	(*LoginGetRequest)(nil),        // 2: logins.LoginGetRequest
	(*LoginGetResponse)(nil),       // 3: logins.LoginGetResponse
	(*LoginUpdateRequest)(nil),     // 4: logins.LoginUpdateRequest
	(*LoginUpdateResponse)(nil),    // 5: logins.LoginUpdateResponse
	(*LoginDeleteRequest)(nil),     // 6: logins.LoginDeleteRequest
	(*LoginDeleteResponse)(nil),    // 7: logins.LoginDeleteResponse
	(*LoginGetListRequest)(nil),    // 8: logins.LoginGetListRequest
	(*LoginGetListResponse)(nil),   // 9: logins.LoginGetListResponse
	(*wrapperspb.StringValue)(nil), // 10: google.protobuf.StringValue
	(*wrapperspb.BytesValue)(nil),  // 11: google.protobuf.BytesValue
	(*wrapperspb.UInt64Value)(nil), // 12: google.protobuf.UInt64Value
}
var file_api_proto_logins_logins_proto_depIdxs = []int32{
	10, // 0: logins.LoginCreateRequest.title:type_name -> google.protobuf.StringValue
	10, // 1: logins.LoginCreateRequest.url:type_name -> google.protobuf.StringValue
	10, // 2: logins.LoginCreateRequest.description:type_name -> google.protobuf.StringValue
	11, // 3: logins.LoginCreateRequest.login_value:type_name -> google.protobuf.BytesValue
	11, // 4: logins.LoginCreateRequest.login_nonce:type_name -> google.protobuf.BytesValue
	12, // 5: logins.LoginCreateRequest.login_key_id:type_name -> google.protobuf.UInt64Value
	11, // 6: logins.LoginCreateRequest.password_value:type_name -> google.protobuf.BytesValue
	11, // 7: logins.LoginCreateRequest.password_nonce:type_name -> google.protobuf.BytesValue
	12, // 8: logins.LoginCreateRequest.password_key_id:type_name -> google.protobuf.UInt64Value
	10, // 9: logins.LoginUpdateRequest.title:type_name -> google.protobuf.StringValue
	10, // 10: logins.LoginUpdateRequest.url:type_name -> google.protobuf.StringValue
	10, // 11: logins.LoginUpdateRequest.description:type_name -> google.protobuf.StringValue
	11, // 12: logins.LoginUpdateRequest.login_value:type_name -> google.protobuf.BytesValue
	11, // 13: logins.LoginUpdateRequest.login_nonce:type_name -> google.protobuf.BytesValue
	12, // 14: logins.LoginUpdateRequest.login_key_id:type_name -> google.protobuf.UInt64Value
	11, // 15: logins.LoginUpdateRequest.password_value:type_name -> google.protobuf.BytesValue
	11, // 16: logins.LoginUpdateRequest.password_nonce:type_name -> google.protobuf.BytesValue
	12, // 17: logins.LoginUpdateRequest.password_key_id:type_name -> google.protobuf.UInt64Value
	3,  // 18: logins.LoginGetListResponse.logins:type_name -> logins.LoginGetResponse
	0,  // 19: logins.LoginService.CreateLogin:input_type -> logins.LoginCreateRequest
	2,  // 20: logins.LoginService.GetLogin:input_type -> logins.LoginGetRequest
	4,  // 21: logins.LoginService.UpdateLogin:input_type -> logins.LoginUpdateRequest
	6,  // 22: logins.LoginService.DeleteLogin:input_type -> logins.LoginDeleteRequest
	8,  // 23: logins.LoginService.GetListLogin:input_type -> logins.LoginGetListRequest
	1,  // 24: logins.LoginService.CreateLogin:output_type -> logins.LoginCreateResponse
	3,  // 25: logins.LoginService.GetLogin:output_type -> logins.LoginGetResponse
	5,  // 26: logins.LoginService.UpdateLogin:output_type -> logins.LoginUpdateResponse
	7,  // 27: logins.LoginService.DeleteLogin:output_type -> logins.LoginDeleteResponse
	9,  // 28: logins.LoginService.GetListLogin:output_type -> logins.LoginGetListResponse
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_proto_logins_logins_proto_init() }
func file_api_proto_logins_logins_proto_init() {
	if File_api_proto_logins_logins_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_logins_logins_proto_rawDesc), len(file_api_proto_logins_logins_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_logins_logins_proto_goTypes,
		DependencyIndexes: file_api_proto_logins_logins_proto_depIdxs,
		MessageInfos:      file_api_proto_logins_logins_proto_msgTypes,
	}.Build()
	File_api_proto_logins_logins_proto = out.File
	file_api_proto_logins_logins_proto_goTypes = nil
	file_api_proto_logins_logins_proto_depIdxs = nil
}
