// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/proto/logins/logins.proto

package logins

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoginService_CreateLogin_FullMethodName  = "/logins.LoginService/CreateLogin"
	LoginService_GetLogin_FullMethodName     = "/logins.LoginService/GetLogin"
	LoginService_UpdateLogin_FullMethodName  = "/logins.LoginService/UpdateLogin"
	LoginService_DeleteLogin_FullMethodName  = "/logins.LoginService/DeleteLogin"
	LoginService_GetListLogin_FullMethodName = "/logins.LoginService/GetListLogin"
)

// LoginServiceClient is the client API for LoginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginServiceClient interface {
	CreateLogin(ctx context.Context, in *LoginCreateRequest, opts ...grpc.CallOption) (*LoginCreateResponse, error)
	GetLogin(ctx context.Context, in *LoginGetRequest, opts ...grpc.CallOption) (*LoginGetResponse, error)
	UpdateLogin(ctx context.Context, in *LoginUpdateRequest, opts ...grpc.CallOption) (*LoginUpdateResponse, error)
	DeleteLogin(ctx context.Context, in *LoginDeleteRequest, opts ...grpc.CallOption) (*LoginDeleteResponse, error)
	GetListLogin(ctx context.Context, in *LoginGetListRequest, opts ...grpc.CallOption) (*LoginGetListResponse, error)
}

type loginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginServiceClient(cc grpc.ClientConnInterface) LoginServiceClient {
	return &loginServiceClient{cc}
}

func (c *loginServiceClient) CreateLogin(ctx context.Context, in *LoginCreateRequest, opts ...grpc.CallOption) (*LoginCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginCreateResponse)
	err := c.cc.Invoke(ctx, LoginService_CreateLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) GetLogin(ctx context.Context, in *LoginGetRequest, opts ...grpc.CallOption) (*LoginGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginGetResponse)
	err := c.cc.Invoke(ctx, LoginService_GetLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) UpdateLogin(ctx context.Context, in *LoginUpdateRequest, opts ...grpc.CallOption) (*LoginUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginUpdateResponse)
	err := c.cc.Invoke(ctx, LoginService_UpdateLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) DeleteLogin(ctx context.Context, in *LoginDeleteRequest, opts ...grpc.CallOption) (*LoginDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginDeleteResponse)
	err := c.cc.Invoke(ctx, LoginService_DeleteLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginServiceClient) GetListLogin(ctx context.Context, in *LoginGetListRequest, opts ...grpc.CallOption) (*LoginGetListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginGetListResponse)
	err := c.cc.Invoke(ctx, LoginService_GetListLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServiceServer is the grpc API for LoginService service.
// All implementations must embed UnimplementedLoginServiceServer
// for forward compatibility.
type LoginServiceServer interface {
	CreateLogin(context.Context, *LoginCreateRequest) (*LoginCreateResponse, error)
	GetLogin(context.Context, *LoginGetRequest) (*LoginGetResponse, error)
	UpdateLogin(context.Context, *LoginUpdateRequest) (*LoginUpdateResponse, error)
	DeleteLogin(context.Context, *LoginDeleteRequest) (*LoginDeleteResponse, error)
	GetListLogin(context.Context, *LoginGetListRequest) (*LoginGetListResponse, error)
	mustEmbedUnimplementedLoginServiceServer()
}

// UnimplementedLoginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoginServiceServer struct{}

func (UnimplementedLoginServiceServer) CreateLogin(context.Context, *LoginCreateRequest) (*LoginCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLogin not implemented")
}
func (UnimplementedLoginServiceServer) GetLogin(context.Context, *LoginGetRequest) (*LoginGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogin not implemented")
}
func (UnimplementedLoginServiceServer) UpdateLogin(context.Context, *LoginUpdateRequest) (*LoginUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLogin not implemented")
}
func (UnimplementedLoginServiceServer) DeleteLogin(context.Context, *LoginDeleteRequest) (*LoginDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLogin not implemented")
}
func (UnimplementedLoginServiceServer) GetListLogin(context.Context, *LoginGetListRequest) (*LoginGetListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListLogin not implemented")
}
func (UnimplementedLoginServiceServer) mustEmbedUnimplementedLoginServiceServer() {}
func (UnimplementedLoginServiceServer) testEmbeddedByValue()                      {}

// UnsafeLoginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginServiceServer will
// result in compilation errors.
type UnsafeLoginServiceServer interface {
	mustEmbedUnimplementedLoginServiceServer()
}

func RegisterLoginServiceServer(s grpc.ServiceRegistrar, srv LoginServiceServer) {
	// If the following call panics, it indicates UnimplementedLoginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoginService_ServiceDesc, srv)
}

func _LoginService_CreateLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).CreateLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_CreateLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).CreateLogin(ctx, req.(*LoginCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_GetLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).GetLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_GetLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).GetLogin(ctx, req.(*LoginGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_UpdateLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).UpdateLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_UpdateLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).UpdateLogin(ctx, req.(*LoginUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_DeleteLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).DeleteLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_DeleteLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).DeleteLogin(ctx, req.(*LoginDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginService_GetListLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginGetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServiceServer).GetListLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoginService_GetListLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServiceServer).GetListLogin(ctx, req.(*LoginGetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoginService_ServiceDesc is the grpc.ServiceDesc for LoginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logins.LoginService",
	HandlerType: (*LoginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLogin",
			Handler:    _LoginService_CreateLogin_Handler,
		},
		{
			MethodName: "GetLogin",
			Handler:    _LoginService_GetLogin_Handler,
		},
		{
			MethodName: "UpdateLogin",
			Handler:    _LoginService_UpdateLogin_Handler,
		},
		{
			MethodName: "DeleteLogin",
			Handler:    _LoginService_DeleteLogin_Handler,
		},
		{
			MethodName: "GetListLogin",
			Handler:    _LoginService_GetListLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/logins/logins.proto",
}
