// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/logins/logins.proto

package logins

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginCreateRequest struct {
	state                  protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Title       *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=title"`
	xxx_hidden_Url         *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=url"`
	xxx_hidden_Description *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=description"`
	xxx_hidden_Login       *wrapperspb.BytesValue  `protobuf:"bytes,4,opt,name=login"`
	xxx_hidden_Password    *wrapperspb.BytesValue  `protobuf:"bytes,5,opt,name=password"`
	xxx_hidden_Nonce       *wrapperspb.BytesValue  `protobuf:"bytes,6,opt,name=nonce"`
	xxx_hidden_KeyId       *wrapperspb.UInt64Value `protobuf:"bytes,7,opt,name=key_id,json=keyId"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginCreateRequest) Reset() {
	*x = LoginCreateRequest{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCreateRequest) ProtoMessage() {}

func (x *LoginCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginCreateRequest) GetTitle() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return nil
}

func (x *LoginCreateRequest) GetUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Url
	}
	return nil
}

func (x *LoginCreateRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return nil
}

func (x *LoginCreateRequest) GetLogin() *wrapperspb.BytesValue {
	if x != nil {
		return x.xxx_hidden_Login
	}
	return nil
}

func (x *LoginCreateRequest) GetPassword() *wrapperspb.BytesValue {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return nil
}

func (x *LoginCreateRequest) GetNonce() *wrapperspb.BytesValue {
	if x != nil {
		return x.xxx_hidden_Nonce
	}
	return nil
}

func (x *LoginCreateRequest) GetKeyId() *wrapperspb.UInt64Value {
	if x != nil {
		return x.xxx_hidden_KeyId
	}
	return nil
}

func (x *LoginCreateRequest) SetTitle(v *wrapperspb.StringValue) {
	x.xxx_hidden_Title = v
}

func (x *LoginCreateRequest) SetUrl(v *wrapperspb.StringValue) {
	x.xxx_hidden_Url = v
}

func (x *LoginCreateRequest) SetDescription(v *wrapperspb.StringValue) {
	x.xxx_hidden_Description = v
}

func (x *LoginCreateRequest) SetLogin(v *wrapperspb.BytesValue) {
	x.xxx_hidden_Login = v
}

func (x *LoginCreateRequest) SetPassword(v *wrapperspb.BytesValue) {
	x.xxx_hidden_Password = v
}

func (x *LoginCreateRequest) SetNonce(v *wrapperspb.BytesValue) {
	x.xxx_hidden_Nonce = v
}

func (x *LoginCreateRequest) SetKeyId(v *wrapperspb.UInt64Value) {
	x.xxx_hidden_KeyId = v
}

func (x *LoginCreateRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Title != nil
}

func (x *LoginCreateRequest) HasUrl() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Url != nil
}

func (x *LoginCreateRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Description != nil
}

func (x *LoginCreateRequest) HasLogin() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Login != nil
}

func (x *LoginCreateRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Password != nil
}

func (x *LoginCreateRequest) HasNonce() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Nonce != nil
}

func (x *LoginCreateRequest) HasKeyId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_KeyId != nil
}

func (x *LoginCreateRequest) ClearTitle() {
	x.xxx_hidden_Title = nil
}

func (x *LoginCreateRequest) ClearUrl() {
	x.xxx_hidden_Url = nil
}

func (x *LoginCreateRequest) ClearDescription() {
	x.xxx_hidden_Description = nil
}

func (x *LoginCreateRequest) ClearLogin() {
	x.xxx_hidden_Login = nil
}

func (x *LoginCreateRequest) ClearPassword() {
	x.xxx_hidden_Password = nil
}

func (x *LoginCreateRequest) ClearNonce() {
	x.xxx_hidden_Nonce = nil
}

func (x *LoginCreateRequest) ClearKeyId() {
	x.xxx_hidden_KeyId = nil
}

type LoginCreateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title       *wrapperspb.StringValue
	Url         *wrapperspb.StringValue
	Description *wrapperspb.StringValue
	Login       *wrapperspb.BytesValue
	Password    *wrapperspb.BytesValue
	Nonce       *wrapperspb.BytesValue
	KeyId       *wrapperspb.UInt64Value
}

func (b0 LoginCreateRequest_builder) Build() *LoginCreateRequest {
	m0 := &LoginCreateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Url = b.Url
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Login = b.Login
	x.xxx_hidden_Password = b.Password
	x.xxx_hidden_Nonce = b.Nonce
	x.xxx_hidden_KeyId = b.KeyId
	return m0
}

type LoginCreateResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Number      uint64                 `protobuf:"varint,1,opt,name=number"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginCreateResponse) Reset() {
	*x = LoginCreateResponse{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginCreateResponse) ProtoMessage() {}

func (x *LoginCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginCreateResponse) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *LoginCreateResponse) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *LoginCreateResponse) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginCreateResponse) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Number = 0
}

type LoginCreateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Number *uint64
}

func (b0 LoginCreateResponse_builder) Build() *LoginCreateResponse {
	m0 := &LoginCreateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Number = *b.Number
	}
	return m0
}

type LoginGetRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Number      uint64                 `protobuf:"varint,1,opt,name=number"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginGetRequest) Reset() {
	*x = LoginGetRequest{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGetRequest) ProtoMessage() {}

func (x *LoginGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginGetRequest) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *LoginGetRequest) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *LoginGetRequest) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginGetRequest) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Number = 0
}

type LoginGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Number *uint64
}

func (b0 LoginGetRequest_builder) Build() *LoginGetRequest {
	m0 := &LoginGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Number = *b.Number
	}
	return m0
}

type LoginGetResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Title       *string                `protobuf:"bytes,1,opt,name=title"`
	xxx_hidden_Number      uint64                 `protobuf:"varint,2,opt,name=number"`
	xxx_hidden_Url         *string                `protobuf:"bytes,3,opt,name=url"`
	xxx_hidden_Description *string                `protobuf:"bytes,4,opt,name=description"`
	xxx_hidden_Login       []byte                 `protobuf:"bytes,5,opt,name=login"`
	xxx_hidden_Password    []byte                 `protobuf:"bytes,6,opt,name=password"`
	xxx_hidden_Nonce       []byte                 `protobuf:"bytes,7,opt,name=nonce"`
	xxx_hidden_KeyId       uint64                 `protobuf:"varint,8,opt,name=key_id,json=keyId"`
	xxx_hidden_CreatedAt   *string                `protobuf:"bytes,9,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt   *string                `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginGetResponse) Reset() {
	*x = LoginGetResponse{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGetResponse) ProtoMessage() {}

func (x *LoginGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginGetResponse) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *LoginGetResponse) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *LoginGetResponse) GetUrl() string {
	if x != nil {
		if x.xxx_hidden_Url != nil {
			return *x.xxx_hidden_Url
		}
		return ""
	}
	return ""
}

func (x *LoginGetResponse) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *LoginGetResponse) GetLogin() []byte {
	if x != nil {
		return x.xxx_hidden_Login
	}
	return nil
}

func (x *LoginGetResponse) GetPassword() []byte {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return nil
}

func (x *LoginGetResponse) GetNonce() []byte {
	if x != nil {
		return x.xxx_hidden_Nonce
	}
	return nil
}

func (x *LoginGetResponse) GetKeyId() uint64 {
	if x != nil {
		return x.xxx_hidden_KeyId
	}
	return 0
}

func (x *LoginGetResponse) GetCreatedAt() string {
	if x != nil {
		if x.xxx_hidden_CreatedAt != nil {
			return *x.xxx_hidden_CreatedAt
		}
		return ""
	}
	return ""
}

func (x *LoginGetResponse) GetUpdatedAt() string {
	if x != nil {
		if x.xxx_hidden_UpdatedAt != nil {
			return *x.xxx_hidden_UpdatedAt
		}
		return ""
	}
	return ""
}

func (x *LoginGetResponse) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 10)
}

func (x *LoginGetResponse) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 10)
}

func (x *LoginGetResponse) SetUrl(v string) {
	x.xxx_hidden_Url = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 10)
}

func (x *LoginGetResponse) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 10)
}

func (x *LoginGetResponse) SetLogin(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Login = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 10)
}

func (x *LoginGetResponse) SetPassword(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Password = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 10)
}

func (x *LoginGetResponse) SetNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Nonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 10)
}

func (x *LoginGetResponse) SetKeyId(v uint64) {
	x.xxx_hidden_KeyId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 10)
}

func (x *LoginGetResponse) SetCreatedAt(v string) {
	x.xxx_hidden_CreatedAt = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 10)
}

func (x *LoginGetResponse) SetUpdatedAt(v string) {
	x.xxx_hidden_UpdatedAt = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 10)
}

func (x *LoginGetResponse) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginGetResponse) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LoginGetResponse) HasUrl() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *LoginGetResponse) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *LoginGetResponse) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *LoginGetResponse) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *LoginGetResponse) HasNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *LoginGetResponse) HasKeyId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *LoginGetResponse) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *LoginGetResponse) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *LoginGetResponse) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Title = nil
}

func (x *LoginGetResponse) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Number = 0
}

func (x *LoginGetResponse) ClearUrl() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Url = nil
}

func (x *LoginGetResponse) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Description = nil
}

func (x *LoginGetResponse) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Login = nil
}

func (x *LoginGetResponse) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Password = nil
}

func (x *LoginGetResponse) ClearNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Nonce = nil
}

func (x *LoginGetResponse) ClearKeyId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_KeyId = 0
}

func (x *LoginGetResponse) ClearCreatedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_CreatedAt = nil
}

func (x *LoginGetResponse) ClearUpdatedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_UpdatedAt = nil
}

type LoginGetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title       *string
	Number      *uint64
	Url         *string
	Description *string
	Login       []byte
	Password    []byte
	Nonce       []byte
	KeyId       *uint64
	CreatedAt   *string
	UpdatedAt   *string
}

func (b0 LoginGetResponse_builder) Build() *LoginGetResponse {
	m0 := &LoginGetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 10)
		x.xxx_hidden_Title = b.Title
	}
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 10)
		x.xxx_hidden_Number = *b.Number
	}
	if b.Url != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 10)
		x.xxx_hidden_Url = b.Url
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 10)
		x.xxx_hidden_Description = b.Description
	}
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 10)
		x.xxx_hidden_Login = b.Login
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 10)
		x.xxx_hidden_Password = b.Password
	}
	if b.Nonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 10)
		x.xxx_hidden_Nonce = b.Nonce
	}
	if b.KeyId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 10)
		x.xxx_hidden_KeyId = *b.KeyId
	}
	if b.CreatedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 10)
		x.xxx_hidden_CreatedAt = b.CreatedAt
	}
	if b.UpdatedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 10)
		x.xxx_hidden_UpdatedAt = b.UpdatedAt
	}
	return m0
}

type LoginUpdateRequest struct {
	state                  protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Title       *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=title"`
	xxx_hidden_Url         *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=url"`
	xxx_hidden_Description *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=description"`
	xxx_hidden_Login       *wrapperspb.BytesValue  `protobuf:"bytes,4,opt,name=login"`
	xxx_hidden_Password    *wrapperspb.BytesValue  `protobuf:"bytes,5,opt,name=password"`
	xxx_hidden_Nonce       *wrapperspb.BytesValue  `protobuf:"bytes,6,opt,name=nonce"`
	xxx_hidden_KeyId       *wrapperspb.UInt64Value `protobuf:"bytes,7,opt,name=key_id,json=keyId"`
	xxx_hidden_Number      uint64                  `protobuf:"varint,8,opt,name=number"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginUpdateRequest) Reset() {
	*x = LoginUpdateRequest{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUpdateRequest) ProtoMessage() {}

func (x *LoginUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginUpdateRequest) GetTitle() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return nil
}

func (x *LoginUpdateRequest) GetUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Url
	}
	return nil
}

func (x *LoginUpdateRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return nil
}

func (x *LoginUpdateRequest) GetLogin() *wrapperspb.BytesValue {
	if x != nil {
		return x.xxx_hidden_Login
	}
	return nil
}

func (x *LoginUpdateRequest) GetPassword() *wrapperspb.BytesValue {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return nil
}

func (x *LoginUpdateRequest) GetNonce() *wrapperspb.BytesValue {
	if x != nil {
		return x.xxx_hidden_Nonce
	}
	return nil
}

func (x *LoginUpdateRequest) GetKeyId() *wrapperspb.UInt64Value {
	if x != nil {
		return x.xxx_hidden_KeyId
	}
	return nil
}

func (x *LoginUpdateRequest) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *LoginUpdateRequest) SetTitle(v *wrapperspb.StringValue) {
	x.xxx_hidden_Title = v
}

func (x *LoginUpdateRequest) SetUrl(v *wrapperspb.StringValue) {
	x.xxx_hidden_Url = v
}

func (x *LoginUpdateRequest) SetDescription(v *wrapperspb.StringValue) {
	x.xxx_hidden_Description = v
}

func (x *LoginUpdateRequest) SetLogin(v *wrapperspb.BytesValue) {
	x.xxx_hidden_Login = v
}

func (x *LoginUpdateRequest) SetPassword(v *wrapperspb.BytesValue) {
	x.xxx_hidden_Password = v
}

func (x *LoginUpdateRequest) SetNonce(v *wrapperspb.BytesValue) {
	x.xxx_hidden_Nonce = v
}

func (x *LoginUpdateRequest) SetKeyId(v *wrapperspb.UInt64Value) {
	x.xxx_hidden_KeyId = v
}

func (x *LoginUpdateRequest) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *LoginUpdateRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Title != nil
}

func (x *LoginUpdateRequest) HasUrl() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Url != nil
}

func (x *LoginUpdateRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Description != nil
}

func (x *LoginUpdateRequest) HasLogin() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Login != nil
}

func (x *LoginUpdateRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Password != nil
}

func (x *LoginUpdateRequest) HasNonce() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Nonce != nil
}

func (x *LoginUpdateRequest) HasKeyId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_KeyId != nil
}

func (x *LoginUpdateRequest) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *LoginUpdateRequest) ClearTitle() {
	x.xxx_hidden_Title = nil
}

func (x *LoginUpdateRequest) ClearUrl() {
	x.xxx_hidden_Url = nil
}

func (x *LoginUpdateRequest) ClearDescription() {
	x.xxx_hidden_Description = nil
}

func (x *LoginUpdateRequest) ClearLogin() {
	x.xxx_hidden_Login = nil
}

func (x *LoginUpdateRequest) ClearPassword() {
	x.xxx_hidden_Password = nil
}

func (x *LoginUpdateRequest) ClearNonce() {
	x.xxx_hidden_Nonce = nil
}

func (x *LoginUpdateRequest) ClearKeyId() {
	x.xxx_hidden_KeyId = nil
}

func (x *LoginUpdateRequest) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Number = 0
}

type LoginUpdateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title       *wrapperspb.StringValue
	Url         *wrapperspb.StringValue
	Description *wrapperspb.StringValue
	Login       *wrapperspb.BytesValue
	Password    *wrapperspb.BytesValue
	Nonce       *wrapperspb.BytesValue
	KeyId       *wrapperspb.UInt64Value
	Number      *uint64
}

func (b0 LoginUpdateRequest_builder) Build() *LoginUpdateRequest {
	m0 := &LoginUpdateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Url = b.Url
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Login = b.Login
	x.xxx_hidden_Password = b.Password
	x.xxx_hidden_Nonce = b.Nonce
	x.xxx_hidden_KeyId = b.KeyId
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_Number = *b.Number
	}
	return m0
}

type LoginUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUpdateResponse) Reset() {
	*x = LoginUpdateResponse{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUpdateResponse) ProtoMessage() {}

func (x *LoginUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LoginUpdateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 LoginUpdateResponse_builder) Build() *LoginUpdateResponse {
	m0 := &LoginUpdateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type LoginDeleteRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Number      uint64                 `protobuf:"varint,1,opt,name=number"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginDeleteRequest) Reset() {
	*x = LoginDeleteRequest{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginDeleteRequest) ProtoMessage() {}

func (x *LoginDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginDeleteRequest) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *LoginDeleteRequest) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *LoginDeleteRequest) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginDeleteRequest) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Number = 0
}

type LoginDeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Number *uint64
}

func (b0 LoginDeleteRequest_builder) Build() *LoginDeleteRequest {
	m0 := &LoginDeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Number = *b.Number
	}
	return m0
}

type LoginDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginDeleteResponse) Reset() {
	*x = LoginDeleteResponse{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginDeleteResponse) ProtoMessage() {}

func (x *LoginDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LoginDeleteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 LoginDeleteResponse_builder) Build() *LoginDeleteResponse {
	m0 := &LoginDeleteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type LoginGetListRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginGetListRequest) Reset() {
	*x = LoginGetListRequest{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginGetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGetListRequest) ProtoMessage() {}

func (x *LoginGetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LoginGetListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 LoginGetListRequest_builder) Build() *LoginGetListRequest {
	m0 := &LoginGetListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type LoginGetListResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Logins *[]*LoginGetResponse   `protobuf:"bytes,1,rep,name=logins"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LoginGetListResponse) Reset() {
	*x = LoginGetListResponse{}
	mi := &file_api_proto_logins_logins_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginGetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGetListResponse) ProtoMessage() {}

func (x *LoginGetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_logins_logins_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginGetListResponse) GetLogins() []*LoginGetResponse {
	if x != nil {
		if x.xxx_hidden_Logins != nil {
			return *x.xxx_hidden_Logins
		}
	}
	return nil
}

func (x *LoginGetListResponse) SetLogins(v []*LoginGetResponse) {
	x.xxx_hidden_Logins = &v
}

type LoginGetListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Logins []*LoginGetResponse
}

func (b0 LoginGetListResponse_builder) Build() *LoginGetListResponse {
	m0 := &LoginGetListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Logins = &b.Logins
	return m0
}

var File_api_proto_logins_logins_proto protoreflect.FileDescriptor

const file_api_proto_logins_logins_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/logins/logins.proto\x12\x06logins\x1a\x1egoogle/protobuf/wrappers.proto\"\x8c\x03\n" +
	"\x12LoginCreateRequest\x122\n" +
	"\x05title\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x05title\x12.\n" +
	"\x03url\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x03url\x12>\n" +
	"\vdescription\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x121\n" +
	"\x05login\x18\x04 \x01(\v2\x1b.google.protobuf.BytesValueR\x05login\x127\n" +
	"\bpassword\x18\x05 \x01(\v2\x1b.google.protobuf.BytesValueR\bpassword\x121\n" +
	"\x05nonce\x18\x06 \x01(\v2\x1b.google.protobuf.BytesValueR\x05nonce\x123\n" +
	"\x06key_id\x18\a \x01(\v2\x1c.google.protobuf.UInt64ValueR\x05keyId\"-\n" +
	"\x13LoginCreateResponse\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\")\n" +
	"\x0fLoginGetRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\"\x91\x02\n" +
	"\x10LoginGetResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x04R\x06number\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05login\x18\x05 \x01(\fR\x05login\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\fR\bpassword\x12\x14\n" +
	"\x05nonce\x18\a \x01(\fR\x05nonce\x12\x15\n" +
	"\x06key_id\x18\b \x01(\x04R\x05keyId\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xa4\x03\n" +
	"\x12LoginUpdateRequest\x122\n" +
	"\x05title\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x05title\x12.\n" +
	"\x03url\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x03url\x12>\n" +
	"\vdescription\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x121\n" +
	"\x05login\x18\x04 \x01(\v2\x1b.google.protobuf.BytesValueR\x05login\x127\n" +
	"\bpassword\x18\x05 \x01(\v2\x1b.google.protobuf.BytesValueR\bpassword\x121\n" +
	"\x05nonce\x18\x06 \x01(\v2\x1b.google.protobuf.BytesValueR\x05nonce\x123\n" +
	"\x06key_id\x18\a \x01(\v2\x1c.google.protobuf.UInt64ValueR\x05keyId\x12\x16\n" +
	"\x06number\x18\b \x01(\x04R\x06number\"\x15\n" +
	"\x13LoginUpdateResponse\",\n" +
	"\x12LoginDeleteRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\"\x15\n" +
	"\x13LoginDeleteResponse\"\x15\n" +
	"\x13LoginGetListRequest\"H\n" +
	"\x14LoginGetListResponse\x120\n" +
	"\x06logins\x18\x01 \x03(\v2\x18.logins.LoginGetResponseR\x06logins2\xf0\x02\n" +
	"\fLoginService\x12F\n" +
	"\vCreateLogin\x12\x1a.logins.LoginCreateRequest\x1a\x1b.logins.LoginCreateResponse\x12=\n" +
	"\bGetLogin\x12\x17.logins.LoginGetRequest\x1a\x18.logins.LoginGetResponse\x12F\n" +
	"\vUpdateLogin\x12\x1a.logins.LoginUpdateRequest\x1a\x1b.logins.LoginUpdateResponse\x12F\n" +
	"\vDeleteLogin\x12\x1a.logins.LoginDeleteRequest\x1a\x1b.logins.LoginDeleteResponse\x12I\n" +
	"\fGetListLogin\x12\x1b.logins.LoginGetListRequest\x1a\x1c.logins.LoginGetListResponseB0Z.github.com/artni96/GophKeeper/api/proto/loginsb\beditionsp\xe8\a"

var file_api_proto_logins_logins_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_logins_logins_proto_goTypes = []any{
	(*LoginCreateRequest)(nil),     // 0: logins.LoginCreateRequest
	(*LoginCreateResponse)(nil),    // 1: logins.LoginCreateResponse
	(*LoginGetRequest)(nil),        // 2: logins.LoginGetRequest
	(*LoginGetResponse)(nil),       // 3: logins.LoginGetResponse
	(*LoginUpdateRequest)(nil),     // 4: logins.LoginUpdateRequest
	(*LoginUpdateResponse)(nil),    // 5: logins.LoginUpdateResponse
	(*LoginDeleteRequest)(nil),     // 6: logins.LoginDeleteRequest
	(*LoginDeleteResponse)(nil),    // 7: logins.LoginDeleteResponse
	(*LoginGetListRequest)(nil),    // 8: logins.LoginGetListRequest
	(*LoginGetListResponse)(nil),   // 9: logins.LoginGetListResponse
	(*wrapperspb.StringValue)(nil), // 10: google.protobuf.StringValue
	(*wrapperspb.BytesValue)(nil),  // 11: google.protobuf.BytesValue
	(*wrapperspb.UInt64Value)(nil), // 12: google.protobuf.UInt64Value
}
var file_api_proto_logins_logins_proto_depIdxs = []int32{
	10, // 0: logins.LoginCreateRequest.title:type_name -> google.protobuf.StringValue
	10, // 1: logins.LoginCreateRequest.url:type_name -> google.protobuf.StringValue
	10, // 2: logins.LoginCreateRequest.description:type_name -> google.protobuf.StringValue
	11, // 3: logins.LoginCreateRequest.login:type_name -> google.protobuf.BytesValue
	11, // 4: logins.LoginCreateRequest.password:type_name -> google.protobuf.BytesValue
	11, // 5: logins.LoginCreateRequest.nonce:type_name -> google.protobuf.BytesValue
	12, // 6: logins.LoginCreateRequest.key_id:type_name -> google.protobuf.UInt64Value
	10, // 7: logins.LoginUpdateRequest.title:type_name -> google.protobuf.StringValue
	10, // 8: logins.LoginUpdateRequest.url:type_name -> google.protobuf.StringValue
	10, // 9: logins.LoginUpdateRequest.description:type_name -> google.protobuf.StringValue
	11, // 10: logins.LoginUpdateRequest.login:type_name -> google.protobuf.BytesValue
	11, // 11: logins.LoginUpdateRequest.password:type_name -> google.protobuf.BytesValue
	11, // 12: logins.LoginUpdateRequest.nonce:type_name -> google.protobuf.BytesValue
	12, // 13: logins.LoginUpdateRequest.key_id:type_name -> google.protobuf.UInt64Value
	3,  // 14: logins.LoginGetListResponse.logins:type_name -> logins.LoginGetResponse
	0,  // 15: logins.LoginService.CreateLogin:input_type -> logins.LoginCreateRequest
	2,  // 16: logins.LoginService.GetLogin:input_type -> logins.LoginGetRequest
	4,  // 17: logins.LoginService.UpdateLogin:input_type -> logins.LoginUpdateRequest
	6,  // 18: logins.LoginService.DeleteLogin:input_type -> logins.LoginDeleteRequest
	8,  // 19: logins.LoginService.GetListLogin:input_type -> logins.LoginGetListRequest
	1,  // 20: logins.LoginService.CreateLogin:output_type -> logins.LoginCreateResponse
	3,  // 21: logins.LoginService.GetLogin:output_type -> logins.LoginGetResponse
	5,  // 22: logins.LoginService.UpdateLogin:output_type -> logins.LoginUpdateResponse
	7,  // 23: logins.LoginService.DeleteLogin:output_type -> logins.LoginDeleteResponse
	9,  // 24: logins.LoginService.GetListLogin:output_type -> logins.LoginGetListResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_proto_logins_logins_proto_init() }
func file_api_proto_logins_logins_proto_init() {
	if File_api_proto_logins_logins_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_logins_logins_proto_rawDesc), len(file_api_proto_logins_logins_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_logins_logins_proto_goTypes,
		DependencyIndexes: file_api_proto_logins_logins_proto_depIdxs,
		MessageInfos:      file_api_proto_logins_logins_proto_msgTypes,
	}.Build()
	File_api_proto_logins_logins_proto = out.File
	file_api_proto_logins_logins_proto_goTypes = nil
	file_api_proto_logins_logins_proto_depIdxs = nil
}
