edition = "2023";

package logins;

import "google/protobuf/wrappers.proto";

option go_package = "github.com/artni96/GophKeeper/api/proto/logins";

service LoginService {
  rpc CreateLogin (LoginCreateRequest) returns (LoginCreateResponse);
  rpc GetLogin (LoginGetRequest) returns (LoginGetResponse);
  rpc UpdateLogin (LoginUpdateRequest) returns (LoginUpdateResponse);
  rpc DeleteLogin (LoginDeleteRequest) returns (LoginDeleteResponse);
  rpc GetListLogin (LoginGetListRequest) returns (LoginGetListResponse);
}

message LoginCreateRequest {
  string title = 1;
  string url = 2;
  string description = 3;
  string login = 4;
  string password = 5;
}

message LoginCreateResponse {
  uint64 number = 1;
}

message LoginGetRequest {
  uint64 number = 1;
}

message LoginGetResponse {
  string title = 1;
  uint64 number = 2;
  string url = 3;
  string description = 4;
  string login = 5;
  string password = 6;
  string created_at = 7;
  string updated_at = 8;
}

message LoginUpdateRequest {
  google.protobuf.StringValue title = 1;
  google.protobuf.StringValue url = 2;
  google.protobuf.StringValue description = 3;
  google.protobuf.StringValue login = 4;
  google.protobuf.StringValue password = 5;
  uint64 number = 6;
}

message LoginUpdateResponse {
}

message LoginDeleteRequest {
  uint64 number = 1;
}

message LoginDeleteResponse {
}

message LoginGetListRequest {
}

message LoginGetListResponse {
  repeated LoginGetListItemResponse logins = 1;
}

message LoginGetListItemResponse {
  string title = 1;
  uint64 number = 2;
  string description = 3;
}
