edition = "2023";

package cards;

import "google/protobuf/wrappers.proto";

option go_package = "github.com/artni96/GophKeeper/api/proto/cards";

service CardService {
  rpc CreateCard (CardCreateRequest) returns (CardCreateResponse);
  rpc GetCard(CardGetRequest) returns (CardGetResponse);
  rpc UpdateCard (CardUpdateRequest) returns (CardUpdateResponse);
  rpc DeleteCard (CardDeleteRequest) returns (CardDeleteResponse);
  rpc GetListCard (CardGetListRequest) returns (CardGetListResponse);
}


message CardCreateRequest {
  google.protobuf.UInt64Value pan = 1;
  google.protobuf.StringValue holder = 2;
  google.protobuf.StringValue expiry_date = 3;
  google.protobuf.UInt64Value cvv = 4;
  google.protobuf.UInt64Value pin = 5;
  google.protobuf.StringValue bank = 6;
  google.protobuf.StringValue brand = 7;
  google.protobuf.StringValue title = 8;
  google.protobuf.StringValue description = 9;
}

message CardCreateResponse {
}

message CardGetRequest {
  uint64 number = 1;
}

message CardGetResponse {
  fixed64 pan = 1;
  string holder = 2;
  string expiry_date = 3;
  uint64 cvv = 4;
  uint64 pin = 5;
  string bank = 6;
  string brand = 7;
  string title = 8;
  string description = 9;
  uint64 number = 10;
  string created_at = 11;
  string updated_at = 12;
}

message CardUpdateRequest {
  google.protobuf.UInt64Value pan = 1;
  google.protobuf.StringValue holder = 2;
  google.protobuf.StringValue expiry_date = 3;
  google.protobuf.UInt64Value cvv = 4;
  google.protobuf.UInt64Value pin = 5;
  google.protobuf.StringValue bank = 6;
  google.protobuf.StringValue brand = 7;
  google.protobuf.StringValue title = 8;
  google.protobuf.StringValue description = 9;
  uint64 number = 10;
}

message CardUpdateResponse {
}

message CardDeleteRequest {
  uint64 number = 1;
}

message CardDeleteResponse {
}

message CardGetListRequest {
}

message CardGetListResponse {
  repeated CardGetListItemResponse cards = 1;
}

message CardGetListItemResponse {
  string title = 1;
  uint64 number = 2;
  string description = 3;
}
