// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/cards/cards.proto

package cards

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardCreateRequest struct {
	state                  protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Pan         *wrapperspb.UInt64Value `protobuf:"bytes,1,opt,name=pan"`
	xxx_hidden_Holder      *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=holder"`
	xxx_hidden_ExpiryDate  *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=expiry_date,json=expiryDate"`
	xxx_hidden_Cvv         *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=cvv"`
	xxx_hidden_Pin         *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=pin"`
	xxx_hidden_Bank        *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=bank"`
	xxx_hidden_Brand       *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=brand"`
	xxx_hidden_Title       *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=title"`
	xxx_hidden_Description *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=description"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CardCreateRequest) Reset() {
	*x = CardCreateRequest{}
	mi := &file_api_proto_cards_cards_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardCreateRequest) ProtoMessage() {}

func (x *CardCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cards_cards_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CardCreateRequest) GetPan() *wrapperspb.UInt64Value {
	if x != nil {
		return x.xxx_hidden_Pan
	}
	return nil
}

func (x *CardCreateRequest) GetHolder() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Holder
	}
	return nil
}

func (x *CardCreateRequest) GetExpiryDate() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_ExpiryDate
	}
	return nil
}

func (x *CardCreateRequest) GetCvv() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Cvv
	}
	return nil
}

func (x *CardCreateRequest) GetPin() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Pin
	}
	return nil
}

func (x *CardCreateRequest) GetBank() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Bank
	}
	return nil
}

func (x *CardCreateRequest) GetBrand() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Brand
	}
	return nil
}

func (x *CardCreateRequest) GetTitle() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return nil
}

func (x *CardCreateRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return nil
}

func (x *CardCreateRequest) SetPan(v *wrapperspb.UInt64Value) {
	x.xxx_hidden_Pan = v
}

func (x *CardCreateRequest) SetHolder(v *wrapperspb.StringValue) {
	x.xxx_hidden_Holder = v
}

func (x *CardCreateRequest) SetExpiryDate(v *wrapperspb.StringValue) {
	x.xxx_hidden_ExpiryDate = v
}

func (x *CardCreateRequest) SetCvv(v *wrapperspb.StringValue) {
	x.xxx_hidden_Cvv = v
}

func (x *CardCreateRequest) SetPin(v *wrapperspb.StringValue) {
	x.xxx_hidden_Pin = v
}

func (x *CardCreateRequest) SetBank(v *wrapperspb.StringValue) {
	x.xxx_hidden_Bank = v
}

func (x *CardCreateRequest) SetBrand(v *wrapperspb.StringValue) {
	x.xxx_hidden_Brand = v
}

func (x *CardCreateRequest) SetTitle(v *wrapperspb.StringValue) {
	x.xxx_hidden_Title = v
}

func (x *CardCreateRequest) SetDescription(v *wrapperspb.StringValue) {
	x.xxx_hidden_Description = v
}

func (x *CardCreateRequest) HasPan() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Pan != nil
}

func (x *CardCreateRequest) HasHolder() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Holder != nil
}

func (x *CardCreateRequest) HasExpiryDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiryDate != nil
}

func (x *CardCreateRequest) HasCvv() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Cvv != nil
}

func (x *CardCreateRequest) HasPin() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Pin != nil
}

func (x *CardCreateRequest) HasBank() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Bank != nil
}

func (x *CardCreateRequest) HasBrand() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Brand != nil
}

func (x *CardCreateRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Title != nil
}

func (x *CardCreateRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Description != nil
}

func (x *CardCreateRequest) ClearPan() {
	x.xxx_hidden_Pan = nil
}

func (x *CardCreateRequest) ClearHolder() {
	x.xxx_hidden_Holder = nil
}

func (x *CardCreateRequest) ClearExpiryDate() {
	x.xxx_hidden_ExpiryDate = nil
}

func (x *CardCreateRequest) ClearCvv() {
	x.xxx_hidden_Cvv = nil
}

func (x *CardCreateRequest) ClearPin() {
	x.xxx_hidden_Pin = nil
}

func (x *CardCreateRequest) ClearBank() {
	x.xxx_hidden_Bank = nil
}

func (x *CardCreateRequest) ClearBrand() {
	x.xxx_hidden_Brand = nil
}

func (x *CardCreateRequest) ClearTitle() {
	x.xxx_hidden_Title = nil
}

func (x *CardCreateRequest) ClearDescription() {
	x.xxx_hidden_Description = nil
}

type CardCreateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Pan         *wrapperspb.UInt64Value
	Holder      *wrapperspb.StringValue
	ExpiryDate  *wrapperspb.StringValue
	Cvv         *wrapperspb.StringValue
	Pin         *wrapperspb.StringValue
	Bank        *wrapperspb.StringValue
	Brand       *wrapperspb.StringValue
	Title       *wrapperspb.StringValue
	Description *wrapperspb.StringValue
}

func (b0 CardCreateRequest_builder) Build() *CardCreateRequest {
	m0 := &CardCreateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Pan = b.Pan
	x.xxx_hidden_Holder = b.Holder
	x.xxx_hidden_ExpiryDate = b.ExpiryDate
	x.xxx_hidden_Cvv = b.Cvv
	x.xxx_hidden_Pin = b.Pin
	x.xxx_hidden_Bank = b.Bank
	x.xxx_hidden_Brand = b.Brand
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Description = b.Description
	return m0
}

type CardCreateResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Number      uint64                 `protobuf:"varint,1,opt,name=number"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CardCreateResponse) Reset() {
	*x = CardCreateResponse{}
	mi := &file_api_proto_cards_cards_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardCreateResponse) ProtoMessage() {}

func (x *CardCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cards_cards_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CardCreateResponse) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *CardCreateResponse) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CardCreateResponse) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CardCreateResponse) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Number = 0
}

type CardCreateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Number *uint64
}

func (b0 CardCreateResponse_builder) Build() *CardCreateResponse {
	m0 := &CardCreateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Number = *b.Number
	}
	return m0
}

type CardGetRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Number      uint64                 `protobuf:"varint,1,opt,name=number"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CardGetRequest) Reset() {
	*x = CardGetRequest{}
	mi := &file_api_proto_cards_cards_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardGetRequest) ProtoMessage() {}

func (x *CardGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cards_cards_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CardGetRequest) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *CardGetRequest) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CardGetRequest) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CardGetRequest) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Number = 0
}

type CardGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Number *uint64
}

func (b0 CardGetRequest_builder) Build() *CardGetRequest {
	m0 := &CardGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Number = *b.Number
	}
	return m0
}

type CardGetResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Pan         uint64                 `protobuf:"fixed64,1,opt,name=pan"`
	xxx_hidden_Holder      *string                `protobuf:"bytes,2,opt,name=holder"`
	xxx_hidden_ExpiryDate  *string                `protobuf:"bytes,3,opt,name=expiry_date,json=expiryDate"`
	xxx_hidden_Cvv         *string                `protobuf:"bytes,4,opt,name=cvv"`
	xxx_hidden_Pin         *string                `protobuf:"bytes,5,opt,name=pin"`
	xxx_hidden_Bank        *string                `protobuf:"bytes,6,opt,name=bank"`
	xxx_hidden_Brand       *string                `protobuf:"bytes,7,opt,name=brand"`
	xxx_hidden_Title       *string                `protobuf:"bytes,8,opt,name=title"`
	xxx_hidden_Description *string                `protobuf:"bytes,9,opt,name=description"`
	xxx_hidden_Number      uint64                 `protobuf:"varint,10,opt,name=number"`
	xxx_hidden_CreatedAt   *string                `protobuf:"bytes,11,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt   *string                `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CardGetResponse) Reset() {
	*x = CardGetResponse{}
	mi := &file_api_proto_cards_cards_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardGetResponse) ProtoMessage() {}

func (x *CardGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cards_cards_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CardGetResponse) GetPan() uint64 {
	if x != nil {
		return x.xxx_hidden_Pan
	}
	return 0
}

func (x *CardGetResponse) GetHolder() string {
	if x != nil {
		if x.xxx_hidden_Holder != nil {
			return *x.xxx_hidden_Holder
		}
		return ""
	}
	return ""
}

func (x *CardGetResponse) GetExpiryDate() string {
	if x != nil {
		if x.xxx_hidden_ExpiryDate != nil {
			return *x.xxx_hidden_ExpiryDate
		}
		return ""
	}
	return ""
}

func (x *CardGetResponse) GetCvv() string {
	if x != nil {
		if x.xxx_hidden_Cvv != nil {
			return *x.xxx_hidden_Cvv
		}
		return ""
	}
	return ""
}

func (x *CardGetResponse) GetPin() string {
	if x != nil {
		if x.xxx_hidden_Pin != nil {
			return *x.xxx_hidden_Pin
		}
		return ""
	}
	return ""
}

func (x *CardGetResponse) GetBank() string {
	if x != nil {
		if x.xxx_hidden_Bank != nil {
			return *x.xxx_hidden_Bank
		}
		return ""
	}
	return ""
}

func (x *CardGetResponse) GetBrand() string {
	if x != nil {
		if x.xxx_hidden_Brand != nil {
			return *x.xxx_hidden_Brand
		}
		return ""
	}
	return ""
}

func (x *CardGetResponse) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *CardGetResponse) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *CardGetResponse) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *CardGetResponse) GetCreatedAt() string {
	if x != nil {
		if x.xxx_hidden_CreatedAt != nil {
			return *x.xxx_hidden_CreatedAt
		}
		return ""
	}
	return ""
}

func (x *CardGetResponse) GetUpdatedAt() string {
	if x != nil {
		if x.xxx_hidden_UpdatedAt != nil {
			return *x.xxx_hidden_UpdatedAt
		}
		return ""
	}
	return ""
}

func (x *CardGetResponse) SetPan(v uint64) {
	x.xxx_hidden_Pan = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 12)
}

func (x *CardGetResponse) SetHolder(v string) {
	x.xxx_hidden_Holder = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 12)
}

func (x *CardGetResponse) SetExpiryDate(v string) {
	x.xxx_hidden_ExpiryDate = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 12)
}

func (x *CardGetResponse) SetCvv(v string) {
	x.xxx_hidden_Cvv = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 12)
}

func (x *CardGetResponse) SetPin(v string) {
	x.xxx_hidden_Pin = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 12)
}

func (x *CardGetResponse) SetBank(v string) {
	x.xxx_hidden_Bank = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 12)
}

func (x *CardGetResponse) SetBrand(v string) {
	x.xxx_hidden_Brand = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 12)
}

func (x *CardGetResponse) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 12)
}

func (x *CardGetResponse) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 12)
}

func (x *CardGetResponse) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 12)
}

func (x *CardGetResponse) SetCreatedAt(v string) {
	x.xxx_hidden_CreatedAt = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 12)
}

func (x *CardGetResponse) SetUpdatedAt(v string) {
	x.xxx_hidden_UpdatedAt = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 12)
}

func (x *CardGetResponse) HasPan() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CardGetResponse) HasHolder() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CardGetResponse) HasExpiryDate() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CardGetResponse) HasCvv() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CardGetResponse) HasPin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CardGetResponse) HasBank() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *CardGetResponse) HasBrand() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *CardGetResponse) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *CardGetResponse) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *CardGetResponse) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *CardGetResponse) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *CardGetResponse) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *CardGetResponse) ClearPan() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Pan = 0
}

func (x *CardGetResponse) ClearHolder() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Holder = nil
}

func (x *CardGetResponse) ClearExpiryDate() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ExpiryDate = nil
}

func (x *CardGetResponse) ClearCvv() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Cvv = nil
}

func (x *CardGetResponse) ClearPin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Pin = nil
}

func (x *CardGetResponse) ClearBank() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Bank = nil
}

func (x *CardGetResponse) ClearBrand() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Brand = nil
}

func (x *CardGetResponse) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Title = nil
}

func (x *CardGetResponse) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_Description = nil
}

func (x *CardGetResponse) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Number = 0
}

func (x *CardGetResponse) ClearCreatedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_CreatedAt = nil
}

func (x *CardGetResponse) ClearUpdatedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_UpdatedAt = nil
}

type CardGetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Pan         *uint64
	Holder      *string
	ExpiryDate  *string
	Cvv         *string
	Pin         *string
	Bank        *string
	Brand       *string
	Title       *string
	Description *string
	Number      *uint64
	CreatedAt   *string
	UpdatedAt   *string
}

func (b0 CardGetResponse_builder) Build() *CardGetResponse {
	m0 := &CardGetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Pan != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 12)
		x.xxx_hidden_Pan = *b.Pan
	}
	if b.Holder != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 12)
		x.xxx_hidden_Holder = b.Holder
	}
	if b.ExpiryDate != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 12)
		x.xxx_hidden_ExpiryDate = b.ExpiryDate
	}
	if b.Cvv != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 12)
		x.xxx_hidden_Cvv = b.Cvv
	}
	if b.Pin != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 12)
		x.xxx_hidden_Pin = b.Pin
	}
	if b.Bank != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 12)
		x.xxx_hidden_Bank = b.Bank
	}
	if b.Brand != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 12)
		x.xxx_hidden_Brand = b.Brand
	}
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 12)
		x.xxx_hidden_Title = b.Title
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 12)
		x.xxx_hidden_Description = b.Description
	}
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 12)
		x.xxx_hidden_Number = *b.Number
	}
	if b.CreatedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 12)
		x.xxx_hidden_CreatedAt = b.CreatedAt
	}
	if b.UpdatedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 12)
		x.xxx_hidden_UpdatedAt = b.UpdatedAt
	}
	return m0
}

type CardUpdateRequest struct {
	state                  protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Pan         *wrapperspb.UInt64Value `protobuf:"bytes,1,opt,name=pan"`
	xxx_hidden_Holder      *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=holder"`
	xxx_hidden_ExpiryDate  *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=expiry_date,json=expiryDate"`
	xxx_hidden_Cvv         *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=cvv"`
	xxx_hidden_Pin         *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=pin"`
	xxx_hidden_Bank        *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=bank"`
	xxx_hidden_Brand       *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=brand"`
	xxx_hidden_Title       *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=title"`
	xxx_hidden_Description *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=description"`
	xxx_hidden_Number      uint64                  `protobuf:"varint,10,opt,name=number"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CardUpdateRequest) Reset() {
	*x = CardUpdateRequest{}
	mi := &file_api_proto_cards_cards_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardUpdateRequest) ProtoMessage() {}

func (x *CardUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cards_cards_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CardUpdateRequest) GetPan() *wrapperspb.UInt64Value {
	if x != nil {
		return x.xxx_hidden_Pan
	}
	return nil
}

func (x *CardUpdateRequest) GetHolder() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Holder
	}
	return nil
}

func (x *CardUpdateRequest) GetExpiryDate() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_ExpiryDate
	}
	return nil
}

func (x *CardUpdateRequest) GetCvv() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Cvv
	}
	return nil
}

func (x *CardUpdateRequest) GetPin() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Pin
	}
	return nil
}

func (x *CardUpdateRequest) GetBank() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Bank
	}
	return nil
}

func (x *CardUpdateRequest) GetBrand() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Brand
	}
	return nil
}

func (x *CardUpdateRequest) GetTitle() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return nil
}

func (x *CardUpdateRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return nil
}

func (x *CardUpdateRequest) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *CardUpdateRequest) SetPan(v *wrapperspb.UInt64Value) {
	x.xxx_hidden_Pan = v
}

func (x *CardUpdateRequest) SetHolder(v *wrapperspb.StringValue) {
	x.xxx_hidden_Holder = v
}

func (x *CardUpdateRequest) SetExpiryDate(v *wrapperspb.StringValue) {
	x.xxx_hidden_ExpiryDate = v
}

func (x *CardUpdateRequest) SetCvv(v *wrapperspb.StringValue) {
	x.xxx_hidden_Cvv = v
}

func (x *CardUpdateRequest) SetPin(v *wrapperspb.StringValue) {
	x.xxx_hidden_Pin = v
}

func (x *CardUpdateRequest) SetBank(v *wrapperspb.StringValue) {
	x.xxx_hidden_Bank = v
}

func (x *CardUpdateRequest) SetBrand(v *wrapperspb.StringValue) {
	x.xxx_hidden_Brand = v
}

func (x *CardUpdateRequest) SetTitle(v *wrapperspb.StringValue) {
	x.xxx_hidden_Title = v
}

func (x *CardUpdateRequest) SetDescription(v *wrapperspb.StringValue) {
	x.xxx_hidden_Description = v
}

func (x *CardUpdateRequest) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 10)
}

func (x *CardUpdateRequest) HasPan() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Pan != nil
}

func (x *CardUpdateRequest) HasHolder() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Holder != nil
}

func (x *CardUpdateRequest) HasExpiryDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiryDate != nil
}

func (x *CardUpdateRequest) HasCvv() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Cvv != nil
}

func (x *CardUpdateRequest) HasPin() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Pin != nil
}

func (x *CardUpdateRequest) HasBank() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Bank != nil
}

func (x *CardUpdateRequest) HasBrand() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Brand != nil
}

func (x *CardUpdateRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Title != nil
}

func (x *CardUpdateRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Description != nil
}

func (x *CardUpdateRequest) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *CardUpdateRequest) ClearPan() {
	x.xxx_hidden_Pan = nil
}

func (x *CardUpdateRequest) ClearHolder() {
	x.xxx_hidden_Holder = nil
}

func (x *CardUpdateRequest) ClearExpiryDate() {
	x.xxx_hidden_ExpiryDate = nil
}

func (x *CardUpdateRequest) ClearCvv() {
	x.xxx_hidden_Cvv = nil
}

func (x *CardUpdateRequest) ClearPin() {
	x.xxx_hidden_Pin = nil
}

func (x *CardUpdateRequest) ClearBank() {
	x.xxx_hidden_Bank = nil
}

func (x *CardUpdateRequest) ClearBrand() {
	x.xxx_hidden_Brand = nil
}

func (x *CardUpdateRequest) ClearTitle() {
	x.xxx_hidden_Title = nil
}

func (x *CardUpdateRequest) ClearDescription() {
	x.xxx_hidden_Description = nil
}

func (x *CardUpdateRequest) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_Number = 0
}

type CardUpdateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Pan         *wrapperspb.UInt64Value
	Holder      *wrapperspb.StringValue
	ExpiryDate  *wrapperspb.StringValue
	Cvv         *wrapperspb.StringValue
	Pin         *wrapperspb.StringValue
	Bank        *wrapperspb.StringValue
	Brand       *wrapperspb.StringValue
	Title       *wrapperspb.StringValue
	Description *wrapperspb.StringValue
	Number      *uint64
}

func (b0 CardUpdateRequest_builder) Build() *CardUpdateRequest {
	m0 := &CardUpdateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Pan = b.Pan
	x.xxx_hidden_Holder = b.Holder
	x.xxx_hidden_ExpiryDate = b.ExpiryDate
	x.xxx_hidden_Cvv = b.Cvv
	x.xxx_hidden_Pin = b.Pin
	x.xxx_hidden_Bank = b.Bank
	x.xxx_hidden_Brand = b.Brand
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Description = b.Description
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 10)
		x.xxx_hidden_Number = *b.Number
	}
	return m0
}

type CardUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardUpdateResponse) Reset() {
	*x = CardUpdateResponse{}
	mi := &file_api_proto_cards_cards_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardUpdateResponse) ProtoMessage() {}

func (x *CardUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cards_cards_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CardUpdateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CardUpdateResponse_builder) Build() *CardUpdateResponse {
	m0 := &CardUpdateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type CardDeleteRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Number      uint64                 `protobuf:"varint,1,opt,name=number"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CardDeleteRequest) Reset() {
	*x = CardDeleteRequest{}
	mi := &file_api_proto_cards_cards_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardDeleteRequest) ProtoMessage() {}

func (x *CardDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cards_cards_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CardDeleteRequest) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *CardDeleteRequest) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CardDeleteRequest) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CardDeleteRequest) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Number = 0
}

type CardDeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Number *uint64
}

func (b0 CardDeleteRequest_builder) Build() *CardDeleteRequest {
	m0 := &CardDeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Number = *b.Number
	}
	return m0
}

type CardDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardDeleteResponse) Reset() {
	*x = CardDeleteResponse{}
	mi := &file_api_proto_cards_cards_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardDeleteResponse) ProtoMessage() {}

func (x *CardDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cards_cards_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CardDeleteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CardDeleteResponse_builder) Build() *CardDeleteResponse {
	m0 := &CardDeleteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type CardGetListRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardGetListRequest) Reset() {
	*x = CardGetListRequest{}
	mi := &file_api_proto_cards_cards_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardGetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardGetListRequest) ProtoMessage() {}

func (x *CardGetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cards_cards_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type CardGetListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 CardGetListRequest_builder) Build() *CardGetListRequest {
	m0 := &CardGetListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type CardGetListResponse struct {
	state            protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Cards *[]*CardGetListItemResponse `protobuf:"bytes,1,rep,name=cards"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CardGetListResponse) Reset() {
	*x = CardGetListResponse{}
	mi := &file_api_proto_cards_cards_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardGetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardGetListResponse) ProtoMessage() {}

func (x *CardGetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cards_cards_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CardGetListResponse) GetCards() []*CardGetListItemResponse {
	if x != nil {
		if x.xxx_hidden_Cards != nil {
			return *x.xxx_hidden_Cards
		}
	}
	return nil
}

func (x *CardGetListResponse) SetCards(v []*CardGetListItemResponse) {
	x.xxx_hidden_Cards = &v
}

type CardGetListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cards []*CardGetListItemResponse
}

func (b0 CardGetListResponse_builder) Build() *CardGetListResponse {
	m0 := &CardGetListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Cards = &b.Cards
	return m0
}

type CardGetListItemResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Title       *string                `protobuf:"bytes,1,opt,name=title"`
	xxx_hidden_Number      uint64                 `protobuf:"varint,2,opt,name=number"`
	xxx_hidden_Description *string                `protobuf:"bytes,3,opt,name=description"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CardGetListItemResponse) Reset() {
	*x = CardGetListItemResponse{}
	mi := &file_api_proto_cards_cards_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardGetListItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardGetListItemResponse) ProtoMessage() {}

func (x *CardGetListItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cards_cards_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CardGetListItemResponse) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *CardGetListItemResponse) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *CardGetListItemResponse) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *CardGetListItemResponse) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *CardGetListItemResponse) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *CardGetListItemResponse) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *CardGetListItemResponse) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CardGetListItemResponse) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CardGetListItemResponse) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CardGetListItemResponse) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Title = nil
}

func (x *CardGetListItemResponse) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Number = 0
}

func (x *CardGetListItemResponse) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Description = nil
}

type CardGetListItemResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title       *string
	Number      *uint64
	Description *string
}

func (b0 CardGetListItemResponse_builder) Build() *CardGetListItemResponse {
	m0 := &CardGetListItemResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Title = b.Title
	}
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Number = *b.Number
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Description = b.Description
	}
	return m0
}

var File_api_proto_cards_cards_proto protoreflect.FileDescriptor

const file_api_proto_cards_cards_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/cards/cards.proto\x12\x05cards\x1a\x1egoogle/protobuf/wrappers.proto\"\xf2\x03\n" +
	"\x11CardCreateRequest\x12.\n" +
	"\x03pan\x18\x01 \x01(\v2\x1c.google.protobuf.UInt64ValueR\x03pan\x124\n" +
	"\x06holder\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x06holder\x12=\n" +
	"\vexpiry_date\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"expiryDate\x12.\n" +
	"\x03cvv\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x03cvv\x12.\n" +
	"\x03pin\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x03pin\x120\n" +
	"\x04bank\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x04bank\x122\n" +
	"\x05brand\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\x05brand\x122\n" +
	"\x05title\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\x05title\x12>\n" +
	"\vdescription\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\",\n" +
	"\x12CardCreateResponse\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\"(\n" +
	"\x0eCardGetRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\"\xb8\x02\n" +
	"\x0fCardGetResponse\x12\x10\n" +
	"\x03pan\x18\x01 \x01(\x06R\x03pan\x12\x16\n" +
	"\x06holder\x18\x02 \x01(\tR\x06holder\x12\x1f\n" +
	"\vexpiry_date\x18\x03 \x01(\tR\n" +
	"expiryDate\x12\x10\n" +
	"\x03cvv\x18\x04 \x01(\tR\x03cvv\x12\x10\n" +
	"\x03pin\x18\x05 \x01(\tR\x03pin\x12\x12\n" +
	"\x04bank\x18\x06 \x01(\tR\x04bank\x12\x14\n" +
	"\x05brand\x18\a \x01(\tR\x05brand\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x16\n" +
	"\x06number\x18\n" +
	" \x01(\x04R\x06number\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"\x8a\x04\n" +
	"\x11CardUpdateRequest\x12.\n" +
	"\x03pan\x18\x01 \x01(\v2\x1c.google.protobuf.UInt64ValueR\x03pan\x124\n" +
	"\x06holder\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x06holder\x12=\n" +
	"\vexpiry_date\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"expiryDate\x12.\n" +
	"\x03cvv\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x03cvv\x12.\n" +
	"\x03pin\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x03pin\x120\n" +
	"\x04bank\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x04bank\x122\n" +
	"\x05brand\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\x05brand\x122\n" +
	"\x05title\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\x05title\x12>\n" +
	"\vdescription\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12\x16\n" +
	"\x06number\x18\n" +
	" \x01(\x04R\x06number\"\x14\n" +
	"\x12CardUpdateResponse\"+\n" +
	"\x11CardDeleteRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\"\x14\n" +
	"\x12CardDeleteResponse\"\x14\n" +
	"\x12CardGetListRequest\"K\n" +
	"\x13CardGetListResponse\x124\n" +
	"\x05cards\x18\x01 \x03(\v2\x1e.cards.CardGetListItemResponseR\x05cards\"i\n" +
	"\x17CardGetListItemResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x04R\x06number\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription2\xd6\x02\n" +
	"\vCardService\x12A\n" +
	"\n" +
	"CreateCard\x12\x18.cards.CardCreateRequest\x1a\x19.cards.CardCreateResponse\x128\n" +
	"\aGetCard\x12\x15.cards.CardGetRequest\x1a\x16.cards.CardGetResponse\x12A\n" +
	"\n" +
	"UpdateCard\x12\x18.cards.CardUpdateRequest\x1a\x19.cards.CardUpdateResponse\x12A\n" +
	"\n" +
	"DeleteCard\x12\x18.cards.CardDeleteRequest\x1a\x19.cards.CardDeleteResponse\x12D\n" +
	"\vGetListCard\x12\x19.cards.CardGetListRequest\x1a\x1a.cards.CardGetListResponseB/Z-github.com/artni96/GophKeeper/api/proto/cardsb\beditionsp\xe8\a"

var file_api_proto_cards_cards_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_cards_cards_proto_goTypes = []any{
	(*CardCreateRequest)(nil),       // 0: cards.CardCreateRequest
	(*CardCreateResponse)(nil),      // 1: cards.CardCreateResponse
	(*CardGetRequest)(nil),          // 2: cards.CardGetRequest
	(*CardGetResponse)(nil),         // 3: cards.CardGetResponse
	(*CardUpdateRequest)(nil),       // 4: cards.CardUpdateRequest
	(*CardUpdateResponse)(nil),      // 5: cards.CardUpdateResponse
	(*CardDeleteRequest)(nil),       // 6: cards.CardDeleteRequest
	(*CardDeleteResponse)(nil),      // 7: cards.CardDeleteResponse
	(*CardGetListRequest)(nil),      // 8: cards.CardGetListRequest
	(*CardGetListResponse)(nil),     // 9: cards.CardGetListResponse
	(*CardGetListItemResponse)(nil), // 10: cards.CardGetListItemResponse
	(*wrapperspb.UInt64Value)(nil),  // 11: google.protobuf.UInt64Value
	(*wrapperspb.StringValue)(nil),  // 12: google.protobuf.StringValue
}
var file_api_proto_cards_cards_proto_depIdxs = []int32{
	11, // 0: cards.CardCreateRequest.pan:type_name -> google.protobuf.UInt64Value
	12, // 1: cards.CardCreateRequest.holder:type_name -> google.protobuf.StringValue
	12, // 2: cards.CardCreateRequest.expiry_date:type_name -> google.protobuf.StringValue
	12, // 3: cards.CardCreateRequest.cvv:type_name -> google.protobuf.StringValue
	12, // 4: cards.CardCreateRequest.pin:type_name -> google.protobuf.StringValue
	12, // 5: cards.CardCreateRequest.bank:type_name -> google.protobuf.StringValue
	12, // 6: cards.CardCreateRequest.brand:type_name -> google.protobuf.StringValue
	12, // 7: cards.CardCreateRequest.title:type_name -> google.protobuf.StringValue
	12, // 8: cards.CardCreateRequest.description:type_name -> google.protobuf.StringValue
	11, // 9: cards.CardUpdateRequest.pan:type_name -> google.protobuf.UInt64Value
	12, // 10: cards.CardUpdateRequest.holder:type_name -> google.protobuf.StringValue
	12, // 11: cards.CardUpdateRequest.expiry_date:type_name -> google.protobuf.StringValue
	12, // 12: cards.CardUpdateRequest.cvv:type_name -> google.protobuf.StringValue
	12, // 13: cards.CardUpdateRequest.pin:type_name -> google.protobuf.StringValue
	12, // 14: cards.CardUpdateRequest.bank:type_name -> google.protobuf.StringValue
	12, // 15: cards.CardUpdateRequest.brand:type_name -> google.protobuf.StringValue
	12, // 16: cards.CardUpdateRequest.title:type_name -> google.protobuf.StringValue
	12, // 17: cards.CardUpdateRequest.description:type_name -> google.protobuf.StringValue
	10, // 18: cards.CardGetListResponse.cards:type_name -> cards.CardGetListItemResponse
	0,  // 19: cards.CardService.CreateCard:input_type -> cards.CardCreateRequest
	2,  // 20: cards.CardService.GetCard:input_type -> cards.CardGetRequest
	4,  // 21: cards.CardService.UpdateCard:input_type -> cards.CardUpdateRequest
	6,  // 22: cards.CardService.DeleteCard:input_type -> cards.CardDeleteRequest
	8,  // 23: cards.CardService.GetListCard:input_type -> cards.CardGetListRequest
	1,  // 24: cards.CardService.CreateCard:output_type -> cards.CardCreateResponse
	3,  // 25: cards.CardService.GetCard:output_type -> cards.CardGetResponse
	5,  // 26: cards.CardService.UpdateCard:output_type -> cards.CardUpdateResponse
	7,  // 27: cards.CardService.DeleteCard:output_type -> cards.CardDeleteResponse
	9,  // 28: cards.CardService.GetListCard:output_type -> cards.CardGetListResponse
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_proto_cards_cards_proto_init() }
func file_api_proto_cards_cards_proto_init() {
	if File_api_proto_cards_cards_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cards_cards_proto_rawDesc), len(file_api_proto_cards_cards_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cards_cards_proto_goTypes,
		DependencyIndexes: file_api_proto_cards_cards_proto_depIdxs,
		MessageInfos:      file_api_proto_cards_cards_proto_msgTypes,
	}.Build()
	File_api_proto_cards_cards_proto = out.File
	file_api_proto_cards_cards_proto_goTypes = nil
	file_api_proto_cards_cards_proto_depIdxs = nil
}
