// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/texts/texts.proto

package texts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextCreateRequest struct {
	state                  protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Title       *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=title"`
	xxx_hidden_Description *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=description"`
	xxx_hidden_Text        *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=text"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TextCreateRequest) Reset() {
	*x = TextCreateRequest{}
	mi := &file_api_proto_texts_texts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextCreateRequest) ProtoMessage() {}

func (x *TextCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_texts_texts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TextCreateRequest) GetTitle() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return nil
}

func (x *TextCreateRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return nil
}

func (x *TextCreateRequest) GetText() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Text
	}
	return nil
}

func (x *TextCreateRequest) SetTitle(v *wrapperspb.StringValue) {
	x.xxx_hidden_Title = v
}

func (x *TextCreateRequest) SetDescription(v *wrapperspb.StringValue) {
	x.xxx_hidden_Description = v
}

func (x *TextCreateRequest) SetText(v *wrapperspb.StringValue) {
	x.xxx_hidden_Text = v
}

func (x *TextCreateRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Title != nil
}

func (x *TextCreateRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Description != nil
}

func (x *TextCreateRequest) HasText() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Text != nil
}

func (x *TextCreateRequest) ClearTitle() {
	x.xxx_hidden_Title = nil
}

func (x *TextCreateRequest) ClearDescription() {
	x.xxx_hidden_Description = nil
}

func (x *TextCreateRequest) ClearText() {
	x.xxx_hidden_Text = nil
}

type TextCreateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title       *wrapperspb.StringValue
	Description *wrapperspb.StringValue
	Text        *wrapperspb.StringValue
}

func (b0 TextCreateRequest_builder) Build() *TextCreateRequest {
	m0 := &TextCreateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Text = b.Text
	return m0
}

type TextCreateResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Number      uint64                 `protobuf:"varint,1,opt,name=number"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TextCreateResponse) Reset() {
	*x = TextCreateResponse{}
	mi := &file_api_proto_texts_texts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextCreateResponse) ProtoMessage() {}

func (x *TextCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_texts_texts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TextCreateResponse) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *TextCreateResponse) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *TextCreateResponse) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TextCreateResponse) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Number = 0
}

type TextCreateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Number *uint64
}

func (b0 TextCreateResponse_builder) Build() *TextCreateResponse {
	m0 := &TextCreateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Number = *b.Number
	}
	return m0
}

type TextGetRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Number      uint64                 `protobuf:"varint,1,opt,name=number"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TextGetRequest) Reset() {
	*x = TextGetRequest{}
	mi := &file_api_proto_texts_texts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextGetRequest) ProtoMessage() {}

func (x *TextGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_texts_texts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TextGetRequest) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *TextGetRequest) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *TextGetRequest) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TextGetRequest) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Number = 0
}

type TextGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Number *uint64
}

func (b0 TextGetRequest_builder) Build() *TextGetRequest {
	m0 := &TextGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Number = *b.Number
	}
	return m0
}

type TextGetResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Title       *string                `protobuf:"bytes,1,opt,name=title"`
	xxx_hidden_Description *string                `protobuf:"bytes,2,opt,name=description"`
	xxx_hidden_Text        *string                `protobuf:"bytes,3,opt,name=text"`
	xxx_hidden_Number      uint64                 `protobuf:"varint,4,opt,name=number"`
	xxx_hidden_CreatedAt   *string                `protobuf:"bytes,5,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt   *string                `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TextGetResponse) Reset() {
	*x = TextGetResponse{}
	mi := &file_api_proto_texts_texts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextGetResponse) ProtoMessage() {}

func (x *TextGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_texts_texts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TextGetResponse) GetTitle() string {
	if x != nil {
		if x.xxx_hidden_Title != nil {
			return *x.xxx_hidden_Title
		}
		return ""
	}
	return ""
}

func (x *TextGetResponse) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *TextGetResponse) GetText() string {
	if x != nil {
		if x.xxx_hidden_Text != nil {
			return *x.xxx_hidden_Text
		}
		return ""
	}
	return ""
}

func (x *TextGetResponse) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *TextGetResponse) GetCreatedAt() string {
	if x != nil {
		if x.xxx_hidden_CreatedAt != nil {
			return *x.xxx_hidden_CreatedAt
		}
		return ""
	}
	return ""
}

func (x *TextGetResponse) GetUpdatedAt() string {
	if x != nil {
		if x.xxx_hidden_UpdatedAt != nil {
			return *x.xxx_hidden_UpdatedAt
		}
		return ""
	}
	return ""
}

func (x *TextGetResponse) SetTitle(v string) {
	x.xxx_hidden_Title = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *TextGetResponse) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *TextGetResponse) SetText(v string) {
	x.xxx_hidden_Text = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *TextGetResponse) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *TextGetResponse) SetCreatedAt(v string) {
	x.xxx_hidden_CreatedAt = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *TextGetResponse) SetUpdatedAt(v string) {
	x.xxx_hidden_UpdatedAt = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *TextGetResponse) HasTitle() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TextGetResponse) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *TextGetResponse) HasText() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TextGetResponse) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TextGetResponse) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *TextGetResponse) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *TextGetResponse) ClearTitle() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Title = nil
}

func (x *TextGetResponse) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Description = nil
}

func (x *TextGetResponse) ClearText() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Text = nil
}

func (x *TextGetResponse) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Number = 0
}

func (x *TextGetResponse) ClearCreatedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_CreatedAt = nil
}

func (x *TextGetResponse) ClearUpdatedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_UpdatedAt = nil
}

type TextGetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title       *string
	Description *string
	Text        *string
	Number      *uint64
	CreatedAt   *string
	UpdatedAt   *string
}

func (b0 TextGetResponse_builder) Build() *TextGetResponse {
	m0 := &TextGetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Title != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Title = b.Title
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Description = b.Description
	}
	if b.Text != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Text = b.Text
	}
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Number = *b.Number
	}
	if b.CreatedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_CreatedAt = b.CreatedAt
	}
	if b.UpdatedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_UpdatedAt = b.UpdatedAt
	}
	return m0
}

type TextUpdateRequest struct {
	state                  protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Title       *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=title"`
	xxx_hidden_Description *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=description"`
	xxx_hidden_Text        *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=text"`
	xxx_hidden_Number      uint64                  `protobuf:"varint,4,opt,name=number"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TextUpdateRequest) Reset() {
	*x = TextUpdateRequest{}
	mi := &file_api_proto_texts_texts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextUpdateRequest) ProtoMessage() {}

func (x *TextUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_texts_texts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TextUpdateRequest) GetTitle() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return nil
}

func (x *TextUpdateRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return nil
}

func (x *TextUpdateRequest) GetText() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Text
	}
	return nil
}

func (x *TextUpdateRequest) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *TextUpdateRequest) SetTitle(v *wrapperspb.StringValue) {
	x.xxx_hidden_Title = v
}

func (x *TextUpdateRequest) SetDescription(v *wrapperspb.StringValue) {
	x.xxx_hidden_Description = v
}

func (x *TextUpdateRequest) SetText(v *wrapperspb.StringValue) {
	x.xxx_hidden_Text = v
}

func (x *TextUpdateRequest) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *TextUpdateRequest) HasTitle() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Title != nil
}

func (x *TextUpdateRequest) HasDescription() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Description != nil
}

func (x *TextUpdateRequest) HasText() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Text != nil
}

func (x *TextUpdateRequest) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *TextUpdateRequest) ClearTitle() {
	x.xxx_hidden_Title = nil
}

func (x *TextUpdateRequest) ClearDescription() {
	x.xxx_hidden_Description = nil
}

func (x *TextUpdateRequest) ClearText() {
	x.xxx_hidden_Text = nil
}

func (x *TextUpdateRequest) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Number = 0
}

type TextUpdateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title       *wrapperspb.StringValue
	Description *wrapperspb.StringValue
	Text        *wrapperspb.StringValue
	Number      *uint64
}

func (b0 TextUpdateRequest_builder) Build() *TextUpdateRequest {
	m0 := &TextUpdateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Text = b.Text
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Number = *b.Number
	}
	return m0
}

type TextUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextUpdateResponse) Reset() {
	*x = TextUpdateResponse{}
	mi := &file_api_proto_texts_texts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextUpdateResponse) ProtoMessage() {}

func (x *TextUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_texts_texts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type TextUpdateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 TextUpdateResponse_builder) Build() *TextUpdateResponse {
	m0 := &TextUpdateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type TextDeleteRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Number      uint64                 `protobuf:"varint,1,opt,name=number"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TextDeleteRequest) Reset() {
	*x = TextDeleteRequest{}
	mi := &file_api_proto_texts_texts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextDeleteRequest) ProtoMessage() {}

func (x *TextDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_texts_texts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TextDeleteRequest) GetNumber() uint64 {
	if x != nil {
		return x.xxx_hidden_Number
	}
	return 0
}

func (x *TextDeleteRequest) SetNumber(v uint64) {
	x.xxx_hidden_Number = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *TextDeleteRequest) HasNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *TextDeleteRequest) ClearNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Number = 0
}

type TextDeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Number *uint64
}

func (b0 TextDeleteRequest_builder) Build() *TextDeleteRequest {
	m0 := &TextDeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Number != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Number = *b.Number
	}
	return m0
}

type TextDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextDeleteResponse) Reset() {
	*x = TextDeleteResponse{}
	mi := &file_api_proto_texts_texts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextDeleteResponse) ProtoMessage() {}

func (x *TextDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_texts_texts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type TextDeleteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 TextDeleteResponse_builder) Build() *TextDeleteResponse {
	m0 := &TextDeleteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type TextGetListRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextGetListRequest) Reset() {
	*x = TextGetListRequest{}
	mi := &file_api_proto_texts_texts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextGetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextGetListRequest) ProtoMessage() {}

func (x *TextGetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_texts_texts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type TextGetListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 TextGetListRequest_builder) Build() *TextGetListRequest {
	m0 := &TextGetListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type TextGetListResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Texts *[]*TextGetResponse    `protobuf:"bytes,1,rep,name=texts"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TextGetListResponse) Reset() {
	*x = TextGetListResponse{}
	mi := &file_api_proto_texts_texts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextGetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextGetListResponse) ProtoMessage() {}

func (x *TextGetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_texts_texts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TextGetListResponse) GetTexts() []*TextGetResponse {
	if x != nil {
		if x.xxx_hidden_Texts != nil {
			return *x.xxx_hidden_Texts
		}
	}
	return nil
}

func (x *TextGetListResponse) SetTexts(v []*TextGetResponse) {
	x.xxx_hidden_Texts = &v
}

type TextGetListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Texts []*TextGetResponse
}

func (b0 TextGetListResponse_builder) Build() *TextGetListResponse {
	m0 := &TextGetListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Texts = &b.Texts
	return m0
}

var File_api_proto_texts_texts_proto protoreflect.FileDescriptor

const file_api_proto_texts_texts_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/texts/texts.proto\x12\x05texts\x1a\x1egoogle/protobuf/wrappers.proto\"\xb9\x01\n" +
	"\x11TextCreateRequest\x122\n" +
	"\x05title\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x05title\x12>\n" +
	"\vdescription\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x120\n" +
	"\x04text\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x04text\",\n" +
	"\x12TextCreateResponse\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\"(\n" +
	"\x0eTextGetRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\"\xb3\x01\n" +
	"\x0fTextGetResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x04R\x06number\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\xd1\x01\n" +
	"\x11TextUpdateRequest\x122\n" +
	"\x05title\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x05title\x12>\n" +
	"\vdescription\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x120\n" +
	"\x04text\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x04text\x12\x16\n" +
	"\x06number\x18\x04 \x01(\x04R\x06number\"\x14\n" +
	"\x12TextUpdateResponse\"+\n" +
	"\x11TextDeleteRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\"\x14\n" +
	"\x12TextDeleteResponse\"\x14\n" +
	"\x12TextGetListRequest\"C\n" +
	"\x13TextGetListResponse\x12,\n" +
	"\x05texts\x18\x01 \x03(\v2\x16.texts.TextGetResponseR\x05texts2\xd6\x02\n" +
	"\vTextService\x12A\n" +
	"\n" +
	"CreateText\x12\x18.texts.TextCreateRequest\x1a\x19.texts.TextCreateResponse\x128\n" +
	"\aGetText\x12\x15.texts.TextGetRequest\x1a\x16.texts.TextGetResponse\x12A\n" +
	"\n" +
	"UpdateText\x12\x18.texts.TextUpdateRequest\x1a\x19.texts.TextUpdateResponse\x12A\n" +
	"\n" +
	"DeleteText\x12\x18.texts.TextDeleteRequest\x1a\x19.texts.TextDeleteResponse\x12D\n" +
	"\vGetListText\x12\x19.texts.TextGetListRequest\x1a\x1a.texts.TextGetListResponseB/Z-github.com/artni96/GophKeeper/api/proto/textsb\beditionsp\xe8\a"

var file_api_proto_texts_texts_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_texts_texts_proto_goTypes = []any{
	(*TextCreateRequest)(nil),      // 0: texts.TextCreateRequest
	(*TextCreateResponse)(nil),     // 1: texts.TextCreateResponse
	(*TextGetRequest)(nil),         // 2: texts.TextGetRequest
	(*TextGetResponse)(nil),        // 3: texts.TextGetResponse
	(*TextUpdateRequest)(nil),      // 4: texts.TextUpdateRequest
	(*TextUpdateResponse)(nil),     // 5: texts.TextUpdateResponse
	(*TextDeleteRequest)(nil),      // 6: texts.TextDeleteRequest
	(*TextDeleteResponse)(nil),     // 7: texts.TextDeleteResponse
	(*TextGetListRequest)(nil),     // 8: texts.TextGetListRequest
	(*TextGetListResponse)(nil),    // 9: texts.TextGetListResponse
	(*wrapperspb.StringValue)(nil), // 10: google.protobuf.StringValue
}
var file_api_proto_texts_texts_proto_depIdxs = []int32{
	10, // 0: texts.TextCreateRequest.title:type_name -> google.protobuf.StringValue
	10, // 1: texts.TextCreateRequest.description:type_name -> google.protobuf.StringValue
	10, // 2: texts.TextCreateRequest.text:type_name -> google.protobuf.StringValue
	10, // 3: texts.TextUpdateRequest.title:type_name -> google.protobuf.StringValue
	10, // 4: texts.TextUpdateRequest.description:type_name -> google.protobuf.StringValue
	10, // 5: texts.TextUpdateRequest.text:type_name -> google.protobuf.StringValue
	3,  // 6: texts.TextGetListResponse.texts:type_name -> texts.TextGetResponse
	0,  // 7: texts.TextService.CreateText:input_type -> texts.TextCreateRequest
	2,  // 8: texts.TextService.GetText:input_type -> texts.TextGetRequest
	4,  // 9: texts.TextService.UpdateText:input_type -> texts.TextUpdateRequest
	6,  // 10: texts.TextService.DeleteText:input_type -> texts.TextDeleteRequest
	8,  // 11: texts.TextService.GetListText:input_type -> texts.TextGetListRequest
	1,  // 12: texts.TextService.CreateText:output_type -> texts.TextCreateResponse
	3,  // 13: texts.TextService.GetText:output_type -> texts.TextGetResponse
	5,  // 14: texts.TextService.UpdateText:output_type -> texts.TextUpdateResponse
	7,  // 15: texts.TextService.DeleteText:output_type -> texts.TextDeleteResponse
	9,  // 16: texts.TextService.GetListText:output_type -> texts.TextGetListResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_texts_texts_proto_init() }
func file_api_proto_texts_texts_proto_init() {
	if File_api_proto_texts_texts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_texts_texts_proto_rawDesc), len(file_api_proto_texts_texts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_texts_texts_proto_goTypes,
		DependencyIndexes: file_api_proto_texts_texts_proto_depIdxs,
		MessageInfos:      file_api_proto_texts_texts_proto_msgTypes,
	}.Build()
	File_api_proto_texts_texts_proto = out.File
	file_api_proto_texts_texts_proto_goTypes = nil
	file_api_proto_texts_texts_proto_depIdxs = nil
}
