// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/proto/texts/texts.proto

package texts

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TextService_CreateText_FullMethodName  = "/texts.TextService/CreateText"
	TextService_GetText_FullMethodName     = "/texts.TextService/GetText"
	TextService_UpdateText_FullMethodName  = "/texts.TextService/UpdateText"
	TextService_DeleteText_FullMethodName  = "/texts.TextService/DeleteText"
	TextService_GetListText_FullMethodName = "/texts.TextService/GetListText"
)

// TextServiceClient is the client API for TextService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextServiceClient interface {
	CreateText(ctx context.Context, in *TextCreateRequest, opts ...grpc.CallOption) (*TextCreateResponse, error)
	GetText(ctx context.Context, in *TextGetRequest, opts ...grpc.CallOption) (*TextGetResponse, error)
	UpdateText(ctx context.Context, in *TextUpdateRequest, opts ...grpc.CallOption) (*TextUpdateResponse, error)
	DeleteText(ctx context.Context, in *TextDeleteRequest, opts ...grpc.CallOption) (*TextDeleteResponse, error)
	GetListText(ctx context.Context, in *TextGetListRequest, opts ...grpc.CallOption) (*TextGetListResponse, error)
}

type textServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTextServiceClient(cc grpc.ClientConnInterface) TextServiceClient {
	return &textServiceClient{cc}
}

func (c *textServiceClient) CreateText(ctx context.Context, in *TextCreateRequest, opts ...grpc.CallOption) (*TextCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextCreateResponse)
	err := c.cc.Invoke(ctx, TextService_CreateText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textServiceClient) GetText(ctx context.Context, in *TextGetRequest, opts ...grpc.CallOption) (*TextGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextGetResponse)
	err := c.cc.Invoke(ctx, TextService_GetText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textServiceClient) UpdateText(ctx context.Context, in *TextUpdateRequest, opts ...grpc.CallOption) (*TextUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextUpdateResponse)
	err := c.cc.Invoke(ctx, TextService_UpdateText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textServiceClient) DeleteText(ctx context.Context, in *TextDeleteRequest, opts ...grpc.CallOption) (*TextDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextDeleteResponse)
	err := c.cc.Invoke(ctx, TextService_DeleteText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textServiceClient) GetListText(ctx context.Context, in *TextGetListRequest, opts ...grpc.CallOption) (*TextGetListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TextGetListResponse)
	err := c.cc.Invoke(ctx, TextService_GetListText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextServiceServer is the grpc API for TextService service.
// All implementations must embed UnimplementedTextServiceServer
// for forward compatibility.
type TextServiceServer interface {
	CreateText(context.Context, *TextCreateRequest) (*TextCreateResponse, error)
	GetText(context.Context, *TextGetRequest) (*TextGetResponse, error)
	UpdateText(context.Context, *TextUpdateRequest) (*TextUpdateResponse, error)
	DeleteText(context.Context, *TextDeleteRequest) (*TextDeleteResponse, error)
	GetListText(context.Context, *TextGetListRequest) (*TextGetListResponse, error)
	mustEmbedUnimplementedTextServiceServer()
}

// UnimplementedTextServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTextServiceServer struct{}

func (UnimplementedTextServiceServer) CreateText(context.Context, *TextCreateRequest) (*TextCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateText not implemented")
}
func (UnimplementedTextServiceServer) GetText(context.Context, *TextGetRequest) (*TextGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetText not implemented")
}
func (UnimplementedTextServiceServer) UpdateText(context.Context, *TextUpdateRequest) (*TextUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateText not implemented")
}
func (UnimplementedTextServiceServer) DeleteText(context.Context, *TextDeleteRequest) (*TextDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteText not implemented")
}
func (UnimplementedTextServiceServer) GetListText(context.Context, *TextGetListRequest) (*TextGetListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListText not implemented")
}
func (UnimplementedTextServiceServer) mustEmbedUnimplementedTextServiceServer() {}
func (UnimplementedTextServiceServer) testEmbeddedByValue()                     {}

// UnsafeTextServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextServiceServer will
// result in compilation errors.
type UnsafeTextServiceServer interface {
	mustEmbedUnimplementedTextServiceServer()
}

func RegisterTextServiceServer(s grpc.ServiceRegistrar, srv TextServiceServer) {
	// If the following call panics, it indicates UnimplementedTextServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TextService_ServiceDesc, srv)
}

func _TextService_CreateText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextServiceServer).CreateText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextService_CreateText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextServiceServer).CreateText(ctx, req.(*TextCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextService_GetText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextServiceServer).GetText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextService_GetText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextServiceServer).GetText(ctx, req.(*TextGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextService_UpdateText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextServiceServer).UpdateText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextService_UpdateText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextServiceServer).UpdateText(ctx, req.(*TextUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextService_DeleteText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextServiceServer).DeleteText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextService_DeleteText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextServiceServer).DeleteText(ctx, req.(*TextDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextService_GetListText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextGetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextServiceServer).GetListText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextService_GetListText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextServiceServer).GetListText(ctx, req.(*TextGetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TextService_ServiceDesc is the grpc.ServiceDesc for TextService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "texts.TextService",
	HandlerType: (*TextServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateText",
			Handler:    _TextService_CreateText_Handler,
		},
		{
			MethodName: "GetText",
			Handler:    _TextService_GetText_Handler,
		},
		{
			MethodName: "UpdateText",
			Handler:    _TextService_UpdateText_Handler,
		},
		{
			MethodName: "DeleteText",
			Handler:    _TextService_DeleteText_Handler,
		},
		{
			MethodName: "GetListText",
			Handler:    _TextService_GetListText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/texts/texts.proto",
}
