// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/health/health.proto

package health

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_health_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_health_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type HealthCheckRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 HealthCheckRequest_builder) Build() *HealthCheckRequest {
	m0 := &HealthCheckRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_health_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_health_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type HealthCheckResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 HealthCheckResponse_builder) Build() *HealthCheckResponse {
	m0 := &HealthCheckResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_api_proto_health_health_proto protoreflect.FileDescriptor

const file_api_proto_health_health_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/health/health.proto\x12\x06health\"\x14\n" +
	"\x12HealthCheckRequest\"\x15\n" +
	"\x13HealthCheckResponse2W\n" +
	"\rHealthService\x12F\n" +
	"\vCheckHealth\x12\x1a.health.HealthCheckRequest\x1a\x1b.health.HealthCheckResponseB0Z.github.com/artni96/GophKeeper/api/proto/healthb\beditionsp\xe8\a"

var file_api_proto_health_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_health_health_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),  // 0: health.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 1: health.HealthCheckResponse
}
var file_api_proto_health_health_proto_depIdxs = []int32{
	0, // 0: health.HealthService.CheckHealth:input_type -> health.HealthCheckRequest
	1, // 1: health.HealthService.CheckHealth:output_type -> health.HealthCheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_health_health_proto_init() }
func file_api_proto_health_health_proto_init() {
	if File_api_proto_health_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_health_health_proto_rawDesc), len(file_api_proto_health_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_health_health_proto_goTypes,
		DependencyIndexes: file_api_proto_health_health_proto_depIdxs,
		MessageInfos:      file_api_proto_health_health_proto_msgTypes,
	}.Build()
	File_api_proto_health_health_proto = out.File
	file_api_proto_health_health_proto_goTypes = nil
	file_api_proto_health_health_proto_depIdxs = nil
}
